### ISSUE TITLE
Support for PowerForms

### ISSUE THREAD

**Issue by imroopesh-ai** [docusign/native-ios-sdk#101]
We are trying to integrate Docusign PowerForms into our healthcare service. We have a use case where all our patients need to eSign couple of forms before the treatment.

It would be great to have the Mobile SDK support PowerForms to easily sign the envelopes.

**Comment by ashokds** [comment]
Hi @imroopesh-ai :

`Powerforms` feature request has been added to the roadmap. Closing it for now as `captive signing` based integration is more favorable at this point.

Thanks for bringing it up.
