### ISSUE TITLE
RadioGroup is not visible on the Documents

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#103]
@ashokds 

We have template in which we are creating all the tabs based on our required. So what we are doing it composing a envelop via template using SDK inbuilt method 

`composeEnvelope`

 As we have similar implementation for pre-filling  DSMText, DSMCheckbox, DSMDate and DSMSignHere all of them are working fine

But When it come to RadioGroup  we are not able the access the all the tabs in RadioGroup. Below is the code for reference

`recipient.tabs.radioGroupTabs`

When I tried access the class DSMRadioGroup It is not in the SDK Version ~> 2.5.3 

 but some How I was trying to built it up via  below code  then also it is not visible 

```
let tab = DSMTabBuilder(for: .radio)
                    .addFrame(frame)
                    .addDocumentId(dsmTab.documentId)
                    .addPageNumber(dsmTab.pageNumber.int32Value)
                    .addName(dsmTab.name)
                    .addRecipientId(dsmTab.recipientId)
                    .build()
```

Please help me how we can achieve the same.

**Comment by mmohareb** [comment]
Hello @pushp1010 
We are trying to replicate this issue on our side,

I just want to understand more about the scenario, is this an existing template that has `radioGroupTab` that you are trying to capture to change, or are you trying to add a new `DSMRadioGroup` to and envelope?

if you have an existing one in the template, you can try fetching it using tabs.allTabs and filter on type .radio, although this will give you the list of DSMRadio not Grouped.

Please help us understand the use case so we can decide if we need to expose these class or not.

Thanks.

cc: @ashokds @divya-vangara

**Comment by pushp1010** [comment]
@mmohareb  @ashokds  @divya-vangara 

we are trying with the below:
> I just want to understand more about the scenario, is this an existing template that has radioGroupTab that you are trying to capture to change, or are you trying to add a new DSMRadioGroup to and envelope?

If you still need some more help to replicate it. To dig down more into it. Let's schedule a call and Please let me know when can we connect **I am available 24*7**?

Thanks,
Pushpendra

**Comment by mmohareb** [comment]
@pushp1010 
we found the root cause why this property is not publicly accessible and will expose it with our next Release.

Thanks

**Comment by pushp1010** [comment]
@mmohareb  When do  you have your next release?

**Comment by mmohareb** [comment]
@pushp1010 
should be around 11/18

**Comment by mmohareb** [comment]
https://github.com/docusign/native-ios-sdk/pull/107

**Comment by pushp1010** [comment]
Now we are able to access  radioGroupTabs via below code but this issue still exists as DSMEnvelopeTab.builder does not

```
private func prepareRadioTabs(recipient: DSMSigner) -> [DSMEnvelopeTab] {
            var envelopeTabs: [DSMEnvelopeTab] = []
            var radios: [DSMEnvelopeTab] = []

            recipient.tabs.radioGroupTabs.forEach { group in
                group.radios.forEach { radioTab in
                    let frame = radioTab.frameAsCGRect()
                    let tab = prepareEnvelopeTab(
                        type: .radio,
                        frame: frame,
                        documentId: radioTab.documentId,
                        pageNumber: radioTab.pageNumber.int32Value,
                        recipientId: radioTab.recipientId,
                        value: ""
                    )
                    radios.append(tab)
                }

                let grouptab = DSMTabBuilder(for: .radioGroup)
                    .addFrame(frame)
                    .addDocumentId(documentId)
                    .addPageNumber(pageNumber)
                    .addName(value)
                    .addRecipientId(recipientId)
                    .addValue(value)
                    .isLocked(false)
                    .build()
                envelopeTabs.append(grouptab)
            }
            return envelopeTabs
        }
```

But DSMTabBuilder does has radioGroup type expose outside to that we can create a radio groups because of which we are still not able to create radio groups and see the Radio groups on the envelope. Please help us with the sample code so that we can achieve the same

<img width="449" alt="Screenshot 2021-11-23 at 7 20 02 PM" src="https://user-images.githubusercontent.com/52121407/143036387-0a24e530-c9b7-4081-b454-49311d1d7dd0.png">
