### ISSUE TITLE
Swift Package Manager support (SPM)

### ISSUE THREAD

**Issue by bencallis** [docusign/native-ios-sdk#105]
We are considering using Docusign in a financial application I am working on. In this application we use SPM for all dependencies. Are there any imminent plans to add support for SPM to the docusign SDK? Without SPM support we may have to look at alternative providers SDKs..

**Comment by ashokds** [comment]
Hi @bencallis : Thanks for bringing the `Swift Package Manager` integration request. This is under discussion.

**Comment by bencallis** [comment]
Thanks for the reply. Please keep us posted on when/if you plan to include support for this.

**Comment by mmohareb** [comment]
Hello @bencallis 

So we are planning to have official support for SPM in the second half of this year, final date to be announced once we come closer to this time frame.

for now you can create a local Swift package using binaryTarget and adding the DocuSignSDK.xcframework
https://github.com/docusign/native-ios-sdk/tree/master/DocuSignSDK.xcframework

you can follow the documentation here
https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

Let us know if you face any issues with this approach.
