### ISSUE TITLE
Create a pre-filled PDF and send it to recipient instantly

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#109]
@ashokds  @mmohareb 

I want to create a pre-filled form and send to the recipients. 

When I tried the same using different type of recipient but end up nowhere
Recipient type
-  CC - it does not show the pre-filled PDF it should PDF with empty fields.
-  inPersonSigner - It does not work as we don't want embedded sign or no Sign tab in the form.
- Signer - It does not work as we don't want signature or  no Sign tab in the form.

For other recipient type I get this error:  `'DSMRecipientBuilderException', reason: 'Unsupported Recipient Type. At the moment only Signers, InPersonSigners and CarbonCopy are allowed.’`

Please help with some code, solution and documentation through which can achieve the above requirement.

**Comment by mmohareb** [comment]
Hello @pushp1010 
can you help us understand better what you are trying to achieve here?
We don't understand how you expect to have any tags for CC recipients?
for IPS and Signers what kind of tabs are you trying to add and are not working?

if you can share a template with the needed requirements we can try to reproduce on our side the scenario and help you what the sample code needed
