### ISSUE TITLE
App is crashing on iOS 15 and above due to DocuSign SDK 2.5.2.

### ISSUE THREAD

**Issue by Rahulp710** [docusign/native-ios-sdk#111]
When try to open DocuSign Template to make signature in mobile application, App getting crashed on iOS 15 and above version devices. But below iOS 15 version devices it is working as expected.

Docusign Version - 2.5.2 installed through cocoa pods.
pod 'DocuSign', '2.5.2'

Error is as below

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <DSMConsumerDisclosureController: 0x7f7a148a5000>'

**Comment by mmohareb** [comment]
Hello @Rahulp710 

This issue was fixed in the latest SDK 2.7.0
