### ISSUE TITLE
Online sign with only access token

### ISSUE THREAD

**Issue by ValeriyJefimov** [docusign/native-ios-sdk#117]
Is there any way to on-line sign only with access token and envelope id, like android guys do? https://github.com/docusign/mobile-android-sdk#signing-online

**Comment by mmohareb** [comment]
Hello @ValeriyJefimov 
You can use this method to start online signing https://developers.docusign.com/docs/mobile-sdks/ios-sdk/reference/interface_d_s_m_envelopes_manager.html#aab7c01da74173cf4d0bdfbf66697b007
But to be able to use it you need to be logged in on the iOS SDK, currently the iOS SDK only provides Login using Access token, but you need to provide additional Info about the account, like account ID, user ID and integrator Key https://developers.docusign.com/docs/mobile-sdks/ios-sdk/reference/interface_d_s_m_manager.html#a0a97228b5b39a66b3ad6339d9e498810

You can use this API to get this user info from the access token https://developers.docusign.com/platform/auth/reference/user-info/ and here is a sample code in our sample app https://github.com/docusign/sample-app-tgk-financial-ios/blob/main/TGK/Network/WebService.swift#L27

For Android Method https://github.com/docusign/mobile-android-sdk#authtoken it internally does this call, but we don't have a similar implementation for it in iOS now, we have it on our long term road map to add more auth options, but don't have a timeline yet for when it will be available.

Let us know if you can make the API call and fetch the userinfo or you need more support for this issue.
