### ISSUE TITLE
RadioGroup button Pre-filling is not working

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#120]
We tried to pre-fill Radio button value in the radio group but it does not work as expected.

When we pre-fill the value it keeps on changing selected value from one radio button to another, if we open the same form again. Moreover, locking radio button functionality is also not working due to which signer is able to change the pre-filled value. please help us with sample code or working sample.

@ashokds  @mmohareb 
Here is the code snippet from our implementation:

```
 var envelopeTabs: [DSMEnvelopeTab] = []
        recipient.tabs.radioGroupTabs.forEach { groupTab in
          for (index, radio) in groupTab.radios.enumerated() {
                let frame = radio.frameAsCGRect()
              let identifier = "\(groupTab.groupName ?? "")\(index + 1)"
                let value = tabs[identifier] ?? radio.value
                let tab = prepareEnvelopeTab(
                    type: .radio,
                    frame: frame,
                    documentId: radio.documentId,
                    pageNumber: radio.pageNumber.int32Value,
                    recipientId: radio.recipientId,
                    value: value
                )
                let radioTab = ((tab as DSMTab) as? DSMRadio)
              	radioTab?.tabLabel = identifier
              	radioTab?.selected = value.isNonEmpty ? true: false
                radioTab?.radioGroupName = groupTab.groupName
                envelopeTabs.append(tab)
            }
        }
        return envelopeTabs

```

**Comment by mmohareb** [comment]
Hello,

I am not sure I fully understand the request, so let me explain what I got from your question.

You want to be able to select multiple radio buttons within a radio button group, that would not work, if you need to have multiple radio buttons selected on the envelope then you need to add them in separate groups because only one radio button can be selected in the group

For the second point, offline signing does not support locking tabs to not allow them to be changed, this is on our road map to fix, let us know if this is a blocking issue for you.

**Comment by mmohareb** [comment]
@pushp1010  can you let us know if this issue is a blocker for your integration or not, if not we will handle it based on our time line.

**Comment by pushp1010** [comment]
@mmohareb 

We are using only one radio group and trying to select one value with in one radio group. But the problem is, when I assign the value for a button from source code, it is not reflected on same radio button in envelope and some other button within same group gets selected.

It is a blocker for us and we would need fix on priority.

We have already raised a separate request for locking tabs of type Radio - case 09332126

**Comment by mmohareb** [comment]
@pushp1010 Thank you for the feedback, we are currently working on a enabling the support for `locked`
we should have a release for this mid next week.

**Comment by pushp1010** [comment]
@mmohareb  But  we still have one more issue what about that?

**Comment by mmohareb** [comment]
@pushp1010 as part of this release we are also validating the selected feature to make sure it works as expected. Once we release it you can re test the scenario again to see if you still see the issue or not.

**Comment by mmohareb** [comment]
@pushp1010 Please find the latest release [v2.11](https://github.com/docusign/native-ios-sdk/releases/tag/v2.11) to address this issue.

Also as mentioned we currently allow only one radio button per group to be selected, /* @note If an existing radio tab is selected in the same radio group, it'll be set as unselected in the process of adding a new radio tab which is selected.*/
so make sure you only set one radio to selected to avoid getting into this situation.

Let us know if we can help.

**Comment by ashokds** [comment]
Hi @pushp1010 :

With `2.11`, following properties on the `radioTab` can be used to customize the radioGroups.

`isLocked(true/false)` -- Locked property customizes the edibility of the radios during. 

`isSelected(true)` -- Selected property allows to pre-select a radio tab in a given group. Selecting a radio tab in a given group makes the previously radios unselected. So there can be only one selected radio tabs in a given radio group.

Sample code to `build()` a radio tab.

```
        let radioTab = DSMTabBuilder(for: .radio)
            .addName("Radio Button 1")
            .addRecipientId(recipientId)
            .addPageNumber(1)
            .addDocumentId("1")
            .addFrame(CGRect(x: 0, y: 0, width: 100, height: 50))
            .addGroupName("Radio test Group")
            .addTabLabel("Radio 1")
            .addValue("Radio 1")
            .isLocked(true)
            .isSelected(true)
            .build()
```

Closing this issue.

Thanks.
