### ISSUE TITLE
v2.11 - App Crash with uncaught exception: 'DSMTabBuilderException', reason: 'Tab Frame is out of page bounds.'

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#123]
It was working fine before the upgrade but we started getting the below crash 2.11 earlier we were using **2.9.**. We are stuck as working functionality stopped working please look into this with priority

It is happening for DSTabtype = DSMTabTypeText 

@mmohareb 

*** Terminating app due to uncaught exception 'DSMTabBuilderException', reason: 'Tab Frame is out of page bounds.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000117ca6ba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000110439be7 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000117ca6845 -[NSException init] + 0
	3   DocuSignSDK                         0x000000011308af6e ArrayByAddingFlexibleSpace + 46606
	4   DocuSignSDK                         0x000000011308abcb ArrayByAddingFlexibleSpace + 45675
	5   DocuSignSDK                         0x0000000113089b5a ArrayByAddingFlexibleSpace + 41466
	6   DocuSignSDK                         0x00000001130949ff ArrayByAddingFlexibleSpace + 86175
	7   Appname                    0x0000000102cea352 $s16Appname16EnvelopesManagerC36presentComposeEnvelopeViewController09envelopesD5Model8onSigned0L9Cancelled0L6Failed7onstart0L13SyncCompletedyAA0cdK0V_ySScyycyycyycySS_S2SSgtctF + 5266
	8   Appname                    0x0000000102776c45 $s16Appname21FinalReviewInteractorC12openDocusign10templateId0H4Name4from17completionHandlerySS_SSSo16UIViewControllerCySbctF + 3365
	9   Appname                    0x00000001027a3daa $s16Appname21FinalReviewInteractorCAA0cD13BusinessLogicA2aDP12openDocusign10templateId0J4Name4from17completionHandlerySS_SSSo16UIViewControllerCySbctFTW + 26
	10  Appname                    0x0000000102f7395d $s16Appname25FinalReviewViewControllerC12openDocusign33_A44FFD5276CD4F5B43000EFA06135AABLL10templateId0P4NameySS_SStF + 365
	11  Appname                    0x0000000102f767c7 $s16Appname25FinalReviewViewControllerC010collectionE0_11willDisplay9forItemAtySo012UICollectionE0C_So0mE4CellC10Foundation9IndexPathVtFySSSgcfU_ + 1271
	12  Appname                    0x0000000102ecbb63 $s16Appname29FinalReviewCollectionViewCellC25reviewAndSignButtonActionyyF + 291
	13  Appname                    0x0000000102ecbbcc $s16Appname29FinalReviewCollectionViewCellC25reviewAndSignButtonActionyyFTo + 28
	14  UIKitCore                           0x000000012d41d26d -[UIApplication sendAction:to:from:forEvent:] + 83
	15  UIKitCore                           0x000000012ccb36e1 -[UIControl sendAction:to:forEvent:] + 110
	16  UIKitCore                           0x000000012ccb3ac3 -[UIControl _sendActionsForEvents:withEvent:] + 332
	17  UIKitCore                           0x000000012ccafffa -[UIButton _sendActionsForEvents:withEvent:] + 148
	18  UIKitCore                           0x000000012ccb2374 -[UIControl touchesEnded:withEvent:] + 488
	19  UIKitCore                           0x000000012cee4a22 _UIGestureEnvironmentUpdate + 9184
	20  UIKitCore                           0x000000012cee21ba -[UIGestureEnvironment _updateForEvent:window:] + 902
	21  UIKitCore                           0x000000012d45fd03 -[UIWindow sendEvent:] + 5267
	22  UIKitCore                           0x000000012d4365b6 -[UIApplication sendEvent:] + 819
	23  SalesforceSDKCore                   0x000000011614fa9c -[SFApplication sendEvent:] + 281
	24  UIKitCore                           0x000000012d4cc4ef __dispatchPreprocessedEventFromEventQueue + 8683
	25  UIKitCore                           0x000000012d4cec75 __processEventQueue + 8579
	26  UIKitCore                           0x000000012d4c5427 __eventFetcherSourceCallback + 240
	27  CoreFoundation                      0x0000000117c14e15 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	28  CoreFoundation                      0x0000000117c14d0d __CFRunLoopDoSource0 + 180
	29  CoreFoundation                      0x0000000117c141e2 __CFRunLoopDoSources0 + 242
	30  CoreFoundation                      0x0000000117c0e941 __CFRunLoopRun + 875
	31  CoreFoundation                      0x0000000117c0e0f3 CFRunLoopRunSpecific + 567
	32  GraphicsServices                    0x0000000119366cd3 GSEventRunModal + 139
	33  UIKitCore                           0x000000012d416f42 -[UIApplication _run] + 928
	34  UIKitCore                           0x000000012d41bb5e UIApplicationMain + 101
	35  Appname                    0x0000000102eff445 main + 229
	36  dyld                                0x000000010d904ee9 start_sim + 10
	37  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by AbdulrahmanGameel** [comment]
hi @pushp1010,

If you can, please open a support case with docusign here: http://support.docusign.com/
They would be best equipped to assist you with the issue ASAP.

Hope this helps.

**Comment by ashokds** [comment]
Hi @pushp1010 :

The tab validation check is throwing an exception (as expected) because one of the tabs is placed outside the bounds of the page. 

`*** Terminating app due to uncaught exception 'DSMTabBuilderException', reason: 'Tab Frame is out of page bounds.'`

The exception is thrown with error that also has `userInfo` to help deduce which tab is failing the validation. Search for `tabId`, `pageWidth` and `pageHeight` properties there to help correct the placement values.

Please make sure that all `X/Y positions` are valid and within the page frame. For example, following values would result in the exception and are invalid:
- Considering a page with `width=600` and `height=800`. When placing a textTab with has `width = 40` and placed at `xPosition = 590` and `yPostion = 200` would end up throwing this exception as textTab horizontal bound check  `rightEdge = 590 + 40 = 630` would exceed page `width = 600`. 
- `-ve value` for `xPosition` or `yPosition`.

As well as ensure that all of the tabs are assigned to a valid page in the document. 

Thanks.

**Comment by ashokds** [comment]
@pushp1010 : 

This check has been updated recently with `v2.11` to address another issue that resulted in `sync` failures. Please upload the template here (or on #127) to help reach a resolution. 

Thanks.

**Comment by pushp1010** [comment]
Thanks for sharing the info on debugging using page width and height.
