### ISSUE TITLE
Random DSMRadio get selected in DSMRadiogroup

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#124]
@mmohareb 

While we are trying to pre-fill the radio button in radios group it keep on selecting the random button we try to find out the reasons 

then we find out the  **groupTab.radios** order keeps on changing in radio groups below is the logs:

```
SMEnvelopeTab groupTab.radios Optional([<DSMRadio: tabLabel: "(null)", tabId: "F5A1BD5C-2121-41D4-8904-7D8212F015EA-18127-0000DE93A9BAE0AC", tabName: "(null)">, <DSMRadio: tabLabel: "(null)", tabId: "B4CEA76F-0A97-43B8-BC54-11B4622044A7-18127-0000DE93A9C4DF6D", tabName: "(null)">])
DSMEnvelopeTab radio.tablabel F5A1BD5C-2121-41D4-8904-7D8212F015EA-18127-0000DE93A9BAE0AC 
DSMEnvelopeTab Selected identifier radioGroupCustomerType1 value true
DSMEnvelopeTab radio.tablabel B4CEA76F-0A97-43B8-BC54-11B4622044A7-18127-0000DE93A9C4DF6D 
DSMEnvelopeTab unSelected identifier radioGroupCustomerType2
DSMEnvelopeTab groupTab.radios Optional([<DSMRadio: tabLabel: "(null)", tabId: "B4CEA76F-0A97-43B8-BC54-11B4622044A7-18127-0000DE93A9C4DF6D", tabName: "(null)">, <DSMRadio: tabLabel: "(null)", tabId: "F5A1BD5C-2121-41D4-8904-7D8212F015EA-18127-0000DE93A9BAE0AC", tabName: "(null)">])
DSMEnvelopeTab radio.tablabel B4CEA76F-0A97-43B8-BC54-11B4622044A7-18127-0000DE93A9C4DF6D 
DSMEnvelopeTab Selected identifier radioGroupCustomerType1 value true
DSMEnvelopeTab radio.tablabel F5A1BD5C-2121-41D4-8904-7D8212F015EA-18127-0000DE93A9BAE0AC 
DSMEnvelopeTab unSelected identifier radioGroupCustomerType2
```

Even more we are not getting any unique identifier **tablabel** and **tabname**  in the radio button of radio group to identify which one to be selected May we are trying something wrong please help us with this. Thanks in advance

**Comment by ivdinkovds** [comment]
Hi @pushp1010, in regards to case 09619415 and the current issue, iOS team devs were notified and will follow up on your question

**Comment by ashokds** [comment]
Hi @pushp1010 :

Please add the code snippet where you are adding `radioTabs` in a `radioGroup`. (Action item on your side to resolve both questions).

As per comment #120 : https://github.com/docusign/native-ios-sdk/issues/120#issuecomment-1152731597, please ensure that a unique `groupName` is used for radios which are part of the same group. I see that you are using `"radioGroupCustomerType1"` and `"radioGroupCustomerType2"` names - it's possible that you are adding these with `.addName("Radio Button 1")` and not `.addGroupName("Radio test Group")`, is that the case? 

Please take a look at this to help clarifying the selection process in radio tabs within a radio group.

![radio-tabs-groups-selection-bg](https://user-images.githubusercontent.com/17131511/176089266-fab44ea6-b3c4-4423-980f-2ce0a1b3fab8.png)

Regarding `tabName` and `tabLabel`, these are optional properties and would be populated only if client-app provides a value for it during the tabBuild process. Are you adding the `label` and `name` while building a tab? 

Note: A unique `tabId` is generated if none is provided. Also, adding code-snippet would help resolve `null` values in the above console message (`tabName: "(null)">, <DSMRadio: tabLabel: "(null)"`).

Thanks.

**Comment by ashokds** [comment]
Hi @pushp1010 :

Were you able to fix the radio tabs assignment and select them as per your need? 

Thanks.

**Comment by mmohareb** [comment]
@pushp1010 
We were able to find an issue on our side causing the tab.value to be missing, we will push a fix in the next release to address this issue, for the time being you can relay on the TabID attribute, this one does not change as long as the tab is not changed in the template.
