### ISSUE TITLE
v2.11 - App Crash with uncaught exception: 'DSMTabBuilderException', reason: 'Tab Frame is out of page bounds.'

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#127]
@ashokds 

It was working fine with previous version of the SDK.

We have the templates created on the web portal and all the textfields are placed within the page. We do not assign the frame explicitly while creating envelope Tab, frame values are the same which we get from the downloaded template tabs.  Everything worked fine till previous version with that placement and we are facing this issue with latest upgrade v2.11.

Is this introduced newly or there is anything which got changed in latest version?

_Originally posted by @pushp1010 in https://github.com/docusign/native-ios-sdk/issues/123#issuecomment-1173529854_

**Comment by ashokds** [comment]
Hi @pushp1010 :

Please upload your template here. It would help investigate this issue on our end. 

Thanks.

**Comment by pushp1010** [comment]
@ashokds 

Thanks for sharing the info on debugging using page width and height.
