### ISSUE TITLE
Open signing view

### ISSUE THREAD

**Issue by patelvivek9115** [docusign/native-ios-sdk#13]
I am getting a document from backend and I need to open signing view so that user can sign the document but not able to find any api related to that in sdk.

**Comment by patelvivek9115** [comment]
@iOSSDK-DocuSign 
I am getting an html string from backend, how can I proceed with it

**Comment by patelvivek9115** [comment]
@iOSSDK-DocuSign The document(envelop) is created using Docusign web and the backend team provide me an api from which I am getting content as a html string. So can you please give some idea how I use this content to take signature of app user

**Comment by patelvivek9115** [comment]
Html content

[HTMLDocusign.txt](https://github.com/docusign/iOS-offline-templates-sdk/files/2829367/HTMLDocusign.txt)

**Comment by iOSSDK-DocuSign** [comment]
@patelvivek9115 , thanks for the details. 

Expending on the last comment "So can you please give some idea how I use this content to take signature of app user".

In this case using iOSSDK (v2.0) won't help you much as there is no current interface in iOSSDK (`DSMEnvelopesManager`) to open the signing view with an existing envelope sent via API. We'll have to look at the alternatives, such as, implementing the Rest API, deep-links, etc to get the signing done on iOS device.

* Is your solution going to be iOS specific or are you looking for integrating signing solution with android app as well in near future?
* Would you like to get signatures using the online or offline signing? 
* Is it ok to use DocuSign App (iOS) to get the signing done? (Say deep-linking via email)

**Comment by patelvivek9115** [comment]
> @patelvivek9115 , thanks for the details.
> 
> Expending on the last comment "So can you please give some idea how I use this content to take signature of app user".
I am sharing html content with you.
[
[HTMLSigning.txt](https://github.com/docusign/iOS-offline-templates-sdk/files/2838371/HTMLSigning.txt)
](url)
> 
> In this case using iOSSDK (v2.0) won't help you much as there is no current interface in iOSSDK (`DSMEnvelopesManager`) to open the signing view with an existing envelope sent via API. We'll have to look at the alternatives, such as, implementing the Rest API, deep-links, etc to get the signing done on iOS device.
> Yes we can if user not need to navigate to other app
> * Is your solution going to be iOS specific or are you looking for integrating signing solution with android app as well in near future?
yes 
> * Would you like to get signatures using the online or offline signing?
It doesn't matter we just want user signature 
> * Is it ok to use DocuSign App (iOS) to get the signing done? (Say deep-linking via email)
No we don't want user need to go outside the app

What i am doing right now I take signing url from the backend which is something like that
https://demo.docusign.net/Signing/StartInSession.aspx?t= and opening into web view and after complete signing the user is navigating to our web page instead of it we want to close the web view and store the data so that we can know that document is signed or not

**Comment by iOSSDK-DocuSign** [comment]
@patelvivek9115 , 

Thanks for further details. Given that you are looking for iOS+Android solution and would like to get the signatures on your app itself (without user requiring app switch). There are more followup questions to understand your need better and suggest an appropriate solution/details. 

Could you please contact us via email on `iOSOfflineTemplatesSdk@docusign.com`. 

Also, is your team (API or Mobile) in touch with a Docusign account manager? Please share the details with the email.
