### ISSUE TITLE
Dismiss captive signing

### ISSUE THREAD

**Issue by ChrisShowoff** [docusign/native-ios-sdk#135]
I am using captive signing from the SDK but want to allow the user to cancel the Docusign presented UIViewcontroller but there is no options given to the user from inside the SDK. I am using the below method to trigger signing

`DSMEnvelopesManager().presentCaptiveSigning(
      withPresenting: self,
      signingUrl: envelope.url,
      envelopeId: envelope.id,
      recipientId: recipientId,
      animated: true) { (viewController, error) in
        print(error)
    }`

Using this method the docusign SDK opens and it covers the entire screen but  the user has no UI to dismiss this viewController. I know we access to the viewController in the callback but how do i display UI for the user to manually exit this flow?

Thanks

**Comment by mmohareb** [comment]
Hello @ChrisShowoff,

Currently we don't provide this feature as a native button, there is an option in the burger menu in the signing screen to decline the signing.
Captive signing urls are intended for one time use, so it didn't make sense to allow a sign later option as there is a need to create a new link to sign anyway.
That said, you can always dismiss the presented view controller in the call back, remove it from it's parent view and present it again as a formsheet or popover that the user can swipe down to dismiss, but that would expire the link that was used to open the signing and will need a new link to start signing again, similar to the sample below.

`DSMEnvelopesManager().presentCaptiveSigning(
                        withPresenting: self,
                        signingUrl: signingUrl,
                        envelopeId: envelopeID,
                        recipientId: nil,
                        animated: true,
                        completion: { viewController, error in
                            guard let viewController = viewController else  {
                                return
                            }
                            viewController.dismiss(animated: false) {
                                viewController.removeFromParent()
                                self.present(viewController, animated: true)
                            }
                        })`

Let us know if this would work for you.

**Comment by mmohareb** [comment]
Hello @ChrisShowoff 

Are we good to close this issue?

**Comment by ChrisShowoff** [comment]
Hey @mmohareb,

Yes sorry was supposed to respond, In our implementation there was no decline to sign option displayed in the hamburger menu hence my question above, I have found the configuration file which has this turned off so we are good to go. You can close this issue and thank you for your help!
