### ISSUE TITLE
Issue with page size while creating envelope.

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#136]
We are using Docusign iOS SDK version 2.12 and facing one issue with page size while creating envelope.

Attached screenshot shows two textfields and the one above works just fine. But for the one which is below, we are getting page size error.

error: ["tabId": 27514CBE-BE64-4CCE-A36F-690C5F34BEC7, "pageHeight": 841.89, "pageWidth": 595.2760000000001]

maxX: 597.0

Page size value which Docusign SDK is generating seems smaller than actual page size. Please help.

<img width="505" alt="MicrosoftTeams-image (22)" src="https://user-images.githubusercontent.com/52121407/206123167-f6a87c1f-88bc-421a-8593-6b2eaedddec1.png">

**Comment by pushp1010** [comment]
@mmohareb  we tried upgrading to 3.0.1. Unfortunately we are facing another  issue mentioned here: https://github.com/docusign/native-ios-sdk/issues/137#issue-1484297525

**Comment by mmohareb** [comment]
Thanks @pushp1010 we are looking into the other issue, can you provide us with a sample template to try to repro the text box size issue on our side?

**Comment by pushp1010** [comment]
@mmohareb  Really sorry! I  won't be able to share it on public platform due to security issues. Please share you personal email address or we can report same through a case. Please suggest.

**Comment by mmohareb** [comment]
@pushp1010 Sure totally understand

If you need to share private data you can send them over to docusignmobilesdk@docusign.com so we can help without compromising the privacy of your data.

**Comment by pushp1010** [comment]
I shared the sample template over the above email address.
