### ISSUE TITLE
Upgraded  to 3.0.3 from 2.12.0 and face below error

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#143]
@mmohareb  pleas help

▿ Optional<Error>
  - some : Error Domain=envelope.resume.error Code=1014 "Envelope is ready for sync and can not be resumed for signing. " UserInfo={NSLocalizedDescription=Envelope is ready for sync and can not be resumed for signing. , NSLocalizedFailureReason=ENVELOPE_RESUME_FAILED}

Code used is same as below 
https://github.com/docusign/native-ios-sdk/issues/137

**Comment by ashokds** [comment]
Hi @pushp1010 :

This is a regression, and we are working on a fix for next release. 

Thanks.

**Comment by pushp1010** [comment]
What is the expected timeline for next release?

**Comment by mmohareb** [comment]
We are expecting to have the next release ready by 2nd week of April

**Comment by mmohareb** [comment]
issue has been addressed in Release 3.0.4
Please retest.

**Comment by pushp1010** [comment]
@mmohareb  we will test and confirm.

**Comment by pushp1010** [comment]
Envelope is ready for sync and can not be resumed for signing issue if fixed now.  

If I compare from previous version. There are change related to checkbox grouping. How are they going to impact existing functionality. Is this going to fix the issue that checkbox were not mandatory and now it will be mandatory?

**Comment by mmohareb** [comment]
Hello @pushp1010 
can explain more what you mean by changes and which versions are you comparing so we can check on our side?

**Comment by pushp1010** [comment]
I am raising a new issue. This can be closed Thanks for the support @mmohareb
