### ISSUE TITLE
 Checkbox group validation is not working

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#145]
@mmohareb @ashokds 

We are currently using iOS SDK 3.0.4 offline signing where checkbox group validations were not working. When we set the validation to "Select atleast one", user is still able to proceed with finish signing without selecting an option in checkbox group.

Please suggest the possible solution for this issue

**Comment by ashokds** [comment]
Hi @pushp1010 : 

Taking a look. 

Thanks for bringing it to our notice.

**Comment by mmohareb** [comment]
Hello @pushp1010,

Thanks for raising the issue.
we were able to identify the root cause and working on a fix now, will let you know once we have the fix ready.

**Comment by mmohareb** [comment]
we are currently testing the fix, will let you know the release date once the testing is confirmed.

**Comment by mmohareb** [comment]
Hello @pushp1010 

our expected delivery date for release 3.0.5 is 2nd week of May
This would include this fix and other new requested features.

**Comment by mmohareb** [comment]
Hello @pushp1010 
We are planning to release it today.
Will post here once the release is published.

**Comment by pushp1010** [comment]
@mmohareb  After updating it 3.0.5 I am getting "A valid recipientId, documentId and pageNumber are required. For RadioTabs value is required." as exception

**Comment by ashokds** [comment]
> Hi @mmohareb
> 
> After updating SDK to 3.0.5 I am getting "A valid recipientId, documentId and pageNumber are required. For RadioTabs value is required." as exception Which is was working fine with 2.12.0.
> 
> Please suggest how we can fix it

> 

Hi @pushp1010 : Please see reply on https://github.com/docusign/native-ios-sdk/issues/155 to make required changes to avoid getting this error.
