### ISSUE TITLE
"Text" is shown in DSMTextTab

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#146]
We have are using Docusign version 2.12.0. Where we have few Editable field to be filled by user. But in these field I have seen "Text" is appearing.

1.  what is "Text" in the DSMTextTab? 
2. is this a placeholder text?
3. is there a way to disable or customise it from Docusign portal or Docusign SDK?

Attached is the screenshot for reference.

<img width="257" alt="Screenshot 2023-04-24 at 1 24 49 PM" src="https://user-images.githubusercontent.com/52121407/233934349-94440364-e6f6-4c7f-8716-d0f97ec3b18b.png">

**Comment by DSDemo-LeandroReis** [comment]
Hi pushp1010,

When working with text tabs the fields are empty/blank by default. If the text is showing during the signing session I'd say that the value property for that tab was set to "text". In this case, you can edit the template you're using (if you're using a template), select the tab (field), and remove the value present.

If using the API you can set the value property for the `textTabs` as you can see in the [API reference documentation](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/) (Schema).

If using the SDK you can set the tab properties as in the example below:

```
Text addedField = new Text {
    DocumentId = "1",
    PageNumber = "1",
    XPosition = "280",
    YPosition = "172",
    Font = "helvetica",
    FontSize = "size14",
    TabLabel = "added text field",
    Height = "23",
    Width = "84",
    Required = "false",
    Bold = "true",
    Value = "",
    Locked = "false",
    TabId = "name",
};
```
I hope the information above helps you, but if you need further assistance, please let me know and it will be a pleasure to understand your issue and help you with it.

**Comment by pushp1010** [comment]
@DSDemo-LeandroReis  Thanks for response. 

We are using offline signing of DocuSign iOS SDK. There two scenarios  in which this "Text" is visible 

-  If we add the text tabs and not setting any value to it then this "Text" is visible like in the above screenshot shared
-  if user tries to enter any value and enter spaces " " then DocuSign SDK  trims that space and again display "Text"

Please let me know if you need any further information

**Comment by pushp1010** [comment]
@mmohareb  any update?

**Comment by mmohareb** [comment]
Hello @pushp1010 
apologies for the late response.
Just to confirm entering any text in the text tab removes the place holder and there is no "Text" added even if you enter `space` after the text.

This behavior is by design and we have a limitation that we can't accept spaces or empty string as a text tab value.
can you explain more about the scenario this behavior is impacting and we can help advice on alternative work around? As of now we will not be able to change this behavior.

you can always share specific use cases confidentially on our docusignmobilesdk@docusign.com inbox.

Thanks.

**Comment by pushp1010** [comment]
@mmohareb  I shared the video how text is appearing on [docusignmobilesdk@docusign.com](mailto:docusignmobilesdk@docusign.com) inbox. Please refer and let us know the your input.
