### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'

### ISSUE THREAD

**Issue by HarRes123** [docusign/native-ios-sdk#148]
@mmohareb I am getting an issue when calling presentSendTemplateControllerWithTemplate from DSMTemplateManager. I manually installed the DocuSignSDK and DocuSignAPI, and ensured that both frameworks are properly embedded into the application. I am using the latest version of both the SDK and the API, which I downloaded directly from this repo yesterday. 

<img width="537" alt="Screenshot 2023-05-17 at 10 46 33 AM" src="https://github.com/docusign/native-ios-sdk/assets/28149735/363c874d-7774-465a-b3d4-34199942fcb6">

I have included the full error message and my code below. Any help would be appreciated 

2023-05-17 10:44:34.188759-0700 Pure[12592:1037640] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x1d2572d94 0x1cb6243d0 0x1cc8af0b4 0x1cc8aefb8 0x110b5426c 0x10c1b6038 0x10c1b7b9c 0x110b5420c 0x110ba0e38 0x110b73990 0x110b73870 0x110b736d8 0x104f3d4c8 0x104f3d9c0 0x110b7274c 0x110bde654 0x110bdf6ec 0x10c1b4520 0x10c1b6038 0x10c1c6798 0x10c1c62dc 0x1d2601d18 0x1d25e3650 0x1d25e84dc 0x20d85435c 0x1d497437c 0x1d4973fe0 0x1dafee0b0 0x104fbfdc0 0x104fbfd38 0x104fbfe94 0x1f1a7cdec)

```
class func getAccessToken(presentationContextProvider: ASWebAuthenticationPresentationContextProviding, completion: @escaping((Bool, String?) -> Void)) {
        guard let authURL = URL(string: "xxx") else { return }
        let scheme = "pure"
        // Initialize the session.

        let session = ASWebAuthenticationSession(url: authURL, callbackURLScheme: scheme) { callbackURL, error in
            // Handle the callback.
            guard let accessToken = callbackURL?.absoluteString.slice(from: "#access_token=", to: "&") else {
                completion(false, nil)
                return
            }
            completion(true, accessToken)
            
        }
        session.presentationContextProvider = presentationContextProvider
        session.start()
    }
    
    class func getUserInfo(accessToken: String, completion: @escaping((Bool, DocuSignAccount?) -> Void)) {
        var request = URLRequest(url: URL(string: "https://account-d.docusign.com/oauth/userinfo")!)
        request.httpMethod = "GET"
        request.setValue("Bearer \(accessToken)", forHTTPHeaderField: "Authorization")
        
        
        let task = URLSession.shared.dataTask(with: request) { (data, response, error) in
            
            if error != nil {
                completion(false, nil)
                return
            }
            
            // if data is nil, throw error
            let statusCode = (response as? HTTPURLResponse)?.statusCode
            guard let data = data, (statusCode ?? 404) < 300 && (statusCode ?? 404) >= 200 else {
                completion(false, nil)
                return
            }

            do {
                let result = try JSONDecoder().decode(DocuSignAccount.self, from: data)
                completion(true, result)
            } catch {
                completion(false, nil)
            }
        }
        task.resume()
    }
    
    class func logInUser(accessToken: String, account: DocuSignAccount, completion: @escaping((Bool, DSMAccountInfo?) -> Void)) {
       
        guard let accountInfo = account.accounts?.first,
              let accountId = accountInfo.accountId,
              let userId = account.sub,
              let userName = accountInfo.accountName,
              let email = account.email else {
            completion(false, nil)
            return
        }
        DSMManager.login(withAccessToken: accessToken, accountId: accountId, userId: userId, userName: userName, email: email, host: URL(string: "https://demo.docusign.net/restapi")!, integratorKey: "xxx") { accountInfo, error in
            guard let accountInfo = accountInfo, error == nil else {
                completion(false, nil)
                return
            }
            completion(true, accountInfo)
        }
    }
    
    class func signDocument(account: DocuSignAccount, presentingViewController: UIViewController, completion: @escaping((UIViewController?, Error?) -> Void)) {
        
        DSMTemplatesManager().cacheTemplate(withId: "xxx") { (error) in
            guard error == nil else {
                print(error)
                return
            }
            let envelopeDefaults = DSMEnvelopeDefaults()

            // Add recipients to Template
            let recipient1 = DSMRecipientDefault()
            recipient1.recipientRoleName = "Pure App User"
            recipient1.recipientSelectorType = .recipientRoleName
            recipient1.recipientName = account.name!
            recipient1.recipientEmail = account.email!

            envelopeDefaults.recipientDefaults = [recipient1]
            let tabs = ["{TAB_LABEL}":"{TAB_VALUE}"]
            envelopeDefaults.tabValueDefaults = tabs
            DSMTemplatesManager().presentSendTemplateControllerWithTemplate(withId: "xxx",
                envelopeDefaults: envelopeDefaults,
                pdfToInsert: nil,
                insertAtPosition: .end,
                signingMode: .online,
                presenting: presentingViewController,
                animated: true,
                completion: { viewController, error  in
                guard error == nil else {
                    print(error)
                    return
                }
                completion(viewController, error)
            })
        }
    }

 @IBAction func signDoc(_ sender: UIButton) {
        DocuSignManager.getAccessToken(presentationContextProvider: self) { success, accessToken in
            guard success, let accessToken = accessToken else {
                //handle error
                UINavigationBar.setAppearance()
                return
            }
            DocuSignManager.getUserInfo(accessToken: accessToken) { success, account in
                guard success, let account = account else {
                    //handle error
                    UINavigationBar.setAppearance()
                    return
                }
                DocuSignManager.logInUser(accessToken: accessToken, account: account) { success, accountInfo in
                    guard success, let accountInfo = accountInfo else {
                        //handle error
                        UINavigationBar.setAppearance()
                        return
                    }
                    print(accountInfo.email)
                    DocuSignManager.signDocument(account: account, presentingViewController: self.delegate!) { vc, error in
                        defer { UINavigationBar.setAppearance() }
                        print(vc)
                    }
                }
            }
        }
    }
```

**Comment by mmohareb** [comment]
Hello @HarRes123 
You will need to add `DocuSignSDK.bundle` to your resources 
![image](https://github.com/docusign/native-ios-sdk/assets/6322177/a4844f5d-0982-490e-a4b4-75a28ba4a13a)

**Comment by HarRes123** [comment]
@mmohareb I was only able to do this: 
<img width="636" alt="Screenshot 2023-05-17 at 11 23 28 AM" src="https://github.com/docusign/native-ios-sdk/assets/28149735/5465d8d7-e04e-44eb-ae69-fabc2460fc23">
How do I get the bundle?

**Comment by mmohareb** [comment]
You can find it here

![image](https://github.com/docusign/native-ios-sdk/assets/6322177/a630bb64-0c87-4852-976b-65598511b6a9)

**Comment by HarRes123** [comment]
I got it! Thank you! Now I'm getting this issue: TEMPLATE_ERROR_INVALID_ROLENAME_RECIPIENTS

**Comment by mmohareb** [comment]
@HarRes123 
Can you share a copy of the template you are using on docusignmobilesdk@docusign.com?
it seems that there is a missing Rolename with one of your recipients that are required by SDK to use the template.

**Comment by mmohareb** [comment]
@HarRes123 when you say a "contract on DocuSign" do you mean that this is an envelope that has already been sent to a specific customer and they need to login with their DocuSign account to sign or is it just a document and you want to create the envelope on the client side and present it to them for signing?

**Comment by HarRes123** [comment]
@mmohareb the latter

**Comment by mmohareb** [comment]
Please take a look at these tutorials
https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/offline-signing-pdf/
https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/offline-signing-template/

also our sample app here has some examples https://github.com/docusign/sample-app-tgk-financial-ios/

**Comment by HarRes123** [comment]
@mmohareb Yes, I follow the second link you sent me, but it requires the user to already be pre-added as a signer, which is not what I want since I won't have the information of every user that needs to agree to this document beforehand.

**Comment by mmohareb** [comment]
Looking at your sample code again, Can you try the role name without spaces?
Also you can share a copy of your template on this email [docusignmobilesdk@docusign.com](mailto:docusignmobilesdk@docusign.com) and we can help investigate what is wrong with it.

**Comment by HarRes123** [comment]
@mmohareb okay, shared. Thank you

**Comment by mmohareb** [comment]
@HarRes123 I have not received the template yet
can double check you sent it to the right email? so we can try to repro the issue on our side

**Comment by HarRes123** [comment]
<img width="1087" alt="Screenshot 2023-05-17 at 12 19 26 PM" src="https://github.com/docusign/native-ios-sdk/assets/28149735/0277a211-cab9-42a8-90fe-e5ae2793d96a">
Is this not correct @mmohareb ?

**Comment by mmohareb** [comment]
@HarRes123 
No, I need you to download (under More) the template and send it as an attachment to this email

**Comment by HarRes123** [comment]
@mmohareb sorry, I sent it.

**Comment by mmohareb** [comment]
got it, will try to repro on our side and get back to you.

**Comment by mmohareb** [comment]
We have found that the template doesn't have tabs added and the SDK does not support freeform templates.
For additional support regarding this specific use case we advise to open a support ticket with our [developer support team](https://developers.docusign.com/support/) and they can assist you better with your work flow.
