### ISSUE TITLE
"Envelope is ready for sync and can not be resumed for signing. " UserInfo={NSLocalizedDescription=Envelope is ready for sync and can not be resumed for signing.

### ISSUE THREAD

**Issue by HarRes123** [docusign/native-ios-sdk#151]
Every time I try to sign an envelope in app, I am presented with the error listed in the title. I'm not sure what to do about this, as I'm following the documentation very closely. Any help would be appreciated. Note that the user is fully signed in before this process begins, and the signer information is being pulled directly from the signed-in account. Additionally, the envelopeId is generated successfully—the issue occurs when calling resumeSigningEnvelope.

```
class func generateEnvelope(account: DocuSignAccount, presentingViewController: UIViewController, completion: @escaping((String?) -> Void)) { 
        let tabA = DSMTabBuilder.init(for: .signHere)
            .addName("signTab1")
            .addRecipientId("1")
            .addDocumentId("1")
            .addPageNumber(1)
            .addFrame(CGRect(x: 75, y: 580, width: 50, height: 40))
            .build()

        let recipientA = DSMRecipientBuilder.init(for: .signer)
            .addRecipientId("1")
            .addRoutingOrder(1)
            .addSignerName(account.givenName! + " " + account.familyName!)
            .addSignerEmail(account.email!)
            .add([tabA])
            .build()

        let filename = "World_Wide_Corp_lorem"

        let filePath = Bundle.init(for: presentingViewController.classForCoder).path(forResource: filename, ofType: "pdf") ?? ""

        let document = DSMDocumentBuilder.init()
            .addName("doc1")
            .addDocumentId("1")
            .addFilePath(filePath)
            .build()


        let envelopeDefinition = DSMEnvelopeBuilder.init()
            .addEnvelopeName("Test Envelope -- name")
            .addEmailSubject("Test Envelope -- Subject")
            .addEmailMessage("Message blurb -- \n -- there goes the docusign email message -- sent via sdk -- ")
            .add([recipientA])
            .add(document)
            .build()

        

        let envManager = DSMEnvelopesManager.init()
        envManager.composeEnvelope(with: envelopeDefinition,
            signingMode: .offline) { (envelopeId, error) in
            guard error == nil else {
                print(error)
                completion(nil)
                return
            }
            print("envelope ID: \(envelopeId)")
            completion(envelopeId)
        }
    }
    
    class func signDoc(envelopeId: String, presentingViewController: UIViewController) {
        let envManager = DSMEnvelopesManager.init()
        envManager.resumeSigningEnvelope(withPresenting: presentingViewController,
            envelopeId: envelopeId) { (viewController, error) in
            guard error == nil else {
                print(error)
                return
            }
        }
    }
```

**Comment by mmohareb** [comment]
Hello @HarRes123 
try to replace this line
`addSignerName(account.givenName! + " " + account.familyName!)`
with
`addSignerName(account.name!)`

This indicated that the signed in user does not have any additional actions to do on the envelope and that the envelope is ready to be sent remotely (either as completed or as ready to be signed by other signers).

Hope this helps.

**Comment by HarRes123** [comment]
@mmohareb unfortunately that did not work

**Comment by mmohareb** [comment]
@HarRes123 
Glad to know you figured out the naming part.
For the other issue you are facing, you can use this delegate method to update the supported orientations to include Landscape for the signingViewController and then set it back to your desired value once the signing is done
`    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
`
For the signing pallet it needs to support Landscape, so you can set only the view that presents the signing view to accept both landscape and then the rest of your app you can remove it once the signing is done.

Closing this ticket as the main issue is fixed.

**Comment by HarRes123** [comment]
@mmohareb what is the class name of the signingViewController? I need to reference it explicitly in the AppDelegate.

**Comment by mmohareb** [comment]
You can use the class of your host app of the ViewController presenting the UIViewController that is returned in the call back you don't have to depend on our class types as these can change and break your code.
