### ISSUE TITLE
I can't open the ios sdk zip

### ISSUE THREAD

**Issue by fischu** [docusign/native-ios-sdk#152]
Hi, 
I need to integrate DocuSign into my SwiftUI app, but there is no support for SMP yet - so I tried the not so nice way of downloading the framework zip and drag it into de project. Problem is I can't unzip it. 
Anyone else with this issue? Or is there a better/working way of adding the framework to you project?

**Comment by mmohareb** [comment]
Hello @fischu 
Can you explain what do you mean by can't unzip it?
The expanded zip should look like the structure below and you should add the 2 xcframeworks to your dependencies and the DocuSignSDK.bundle to your project resources

**Comment by ByungjaeChung** [comment]
Hi @fischu,
I had no issue with downloading the project and unzip it through Windows built-in feature: https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc 
Could you please try unzipping it this way?

**Comment by fischu** [comment]
@mmohareb I'm working on a mac, because of iOS development requirements, and I can't unzip the file - i get an error saying: "unable to expand "DocuSignSDK.zip". it is in an unsupported format." 
@ByungjaeChung I don't have a Windows machine, I'm using the MacOS built-in feature. 
I believe since this is a framework for iOS, it should be working on a mac system, no?

**Comment by fischu** [comment]
@mmohareb I just tried it on a team mate's Windows machine and it throws a similar error as on Mac: "Windows cannot open the folder. The Compressed (zipped) Folder "DocuSignSDK.zip" is invalid."

**Comment by mmohareb** [comment]
@fischu 
can you try to download it from this [link](https://docucdn-a.akamaihd.net/prod/docusigniossdk/3.0.5/DocuSignSDK.zip)?
also confirm that the file downloaded is matching the size 172MB?

**Comment by mmohareb** [comment]
@fischu 
I just tried it from github and it worked fine
might be just a glitch, glad it worked out for you
closing the ticket
