### ISSUE TITLE
"A valid recipientId, documentId and pageNumber are required. For RadioTabs value is required." as exception

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#155]
Hi @mmohareb 

https://github.com/docusign/native-ios-sdk/issues/145 

After updating SDK to 3.0.5 I am getting "A valid recipientId, documentId and pageNumber are required. For RadioTabs value is required." as exception Which is was working fine with 2.12.0. 

Please suggest how we can fix it

**Comment by ashokds** [comment]
Hi @pushp1010 :

We have added support for the `Conditional Tabs` in the 3.x release. Earlier with 2.x versions, the `value` for RadioTabs were not used. So you would need to update the Envelope-Defaults to get rid of the following error:



If you are using `radioTabs` (`DSMTabTypeRadio`), please ensure that `value` property (`"Radio1"`, `"Radio2"`, etc) is set in the the defaults for the radio tabs in the group. Here is how you could find it:


1. In the template JSON look for `"value":"Radio1"`  (Radio1 is default value assigned to the first radio tab in the group, you could edit it if needed).

```
{
	"documentId": "1",
	"groupName": "##parentd0adb88f-06da-49a7-8d73-c160fa23a17e##Radio Group bce55a5d-c18d-45f6-a4ad-491e745b256f",
	"originalValue": "",
	"radios": [{
		"bold": "false",
		"font": "lucidaconsole",
		"fontColor": "black",
		"fontSize": "size9",
		"italic": "false",
		"locked": "false",
		"pageNumber": "1",
		"required": "true",
		"selected": "false",
		"tabId": "d0adb88f-06da-49a7-8d73-c160fa23a17e",
		"underline": "false",
		"value": "Radio1",
		"xPosition": "139",
		"yPosition": "315"
	}],
	"recipientId": "46203750",
	"requireAll": "false",
	"requireInitialOnSharedChange": "false",
	"shared": "false",
	"tabType": "radiogroup",
	"templateLocked": "false",
	"templateRequired": "false",
	"value": ""
}
```

2. Finding Radio Tab Value on DocuSign Web (Template example here):

![Setting-Radio-Tab-Values-In-A-Group](https://github.com/docusign/native-ios-sdk/assets/17131511/7c4a209b-1989-49db-8ca4-cc604dd9d51c)


Also note that RadioTabs, like any other tabs added to the envelope-defaults setup, also need `recipientId`, `documentId` and `pageNumber` are non-nil/non-empty values. 


Let us know if this works for you,

**Comment by ashokds** [comment]
Note: You could also use the latest SDK version `3.1.0` - June Release.

Here is the changeLog: https://github.com/docusign/native-ios-sdk/blob/master/CHANGELOG.md

**Comment by pushp1010** [comment]
> Note: You could also use the latest SDK version `3.1.0` - June Release.
> 
> Here is the changeLog: https://github.com/docusign/native-ios-sdk/blob/master/CHANGELOG.md

We count not use it currently as it need an update related to authentication

**Comment by pushp1010** [comment]
> Hi @pushp1010 :
> 
> We have added support for the `Conditional Tabs` in the 3.x release. Earlier with 2.x versions, the `value` for RadioTabs were not used. So you would need to update the Envelope-Defaults to get rid of the following error:
> 
> If you are using `radioTabs` (`DSMTabTypeRadio`), please ensure that `value` property (`"Radio1"`, `"Radio2"`, etc) is set in the the defaults for the radio tabs in the group. If you are creating the envelope & tabs programmatically, assign a unique value for individual radio tabs in the group. For other cases, here is how you could find it:
> 
> 1. In the template JSON look for `"value":"Radio1"`  (Radio1 is default value assigned to the first radio tab in the group, you could edit it if needed).
> 
> ```
> {
> 	"documentId": "1",
> 	"groupName": "##parentd0adb88f-06da-49a7-8d73-c160fa23a17e##Radio Group bce55a5d-c18d-45f6-a4ad-491e745b256f",
> 	"originalValue": "",
> 	"radios": [{
> 		"bold": "false",
> 		"font": "lucidaconsole",
> 		"fontColor": "black",
> 		"fontSize": "size9",
> 		"italic": "false",
> 		"locked": "false",
> 		"pageNumber": "1",
> 		"required": "true",
> 		"selected": "false",
> 		"tabId": "d0adb88f-06da-49a7-8d73-c160fa23a17e",
> 		"underline": "false",
> 		"value": "Radio1",
> 		"xPosition": "139",
> 		"yPosition": "315"
> 	}],
> 	"recipientId": "46203750",
> 	"requireAll": "false",
> 	"requireInitialOnSharedChange": "false",
> 	"shared": "false",
> 	"tabType": "radiogroup",
> 	"templateLocked": "false",
> 	"templateRequired": "false",
> 	"value": ""
> }
> ```
> 
>  2. Finding Radio Tab Value on DocuSign Web (Template example here):
> 
> ![Setting-Radio-Tab-Values-In-A-Group](https://user-images.githubusercontent.com/17131511/251865833-7c4a209b-1989-49db-8ca4-cc604dd9d51c.jpg)
> 
> Also note that RadioTabs, like any other tabs added to the envelope-defaults setup, also need `recipientId`, `documentId` and `pageNumber` are non-nil/non-empty values.
> 
> Let us know if this works for you,

Let me check it

**Comment by ashokds** [comment]
@pushp1010, Did you get a chance to check it?
