### ISSUE TITLE
Change the alert message after offline signing

### ISSUE THREAD

**Issue by sun-sational** [docusign/native-ios-sdk#156]
Is it possible to customize the message displayed in the alert that appears after offline document signing? Alternatively, can the alert be hidden entirely? I'm referring to the alert shown in the image below.

<img src="https://github.com/docusign/native-ios-sdk/assets/20676379/60f71fc0-2a7a-45c8-8151-69bab25810af" width="200">

**Comment by DocuSignEric** [comment]
Hi @sun-sational,

I hope you are well,

Unfortunately, no, it is not possible to customize the message displayed in the alert that appears after offline document signing, nor is it possible to hide the alert entirely.

Regards,

Eric | DocuSign

**Comment by mmohareb** [comment]
hello @sun-sational 

There is one setting that would disable all alerts in offline signing, not just this one
`DSM_SETUP_OFFLINE_SIGNING_HIDE_ALERTS_KEY`
https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsm_setup_offline_signing_hide_alerts_key

This could be an option as there is no way to alter the text, or hide this specific alert as @DocuSignEric  mentioned.

Thanks,
Mina.

**Comment by sun-sational** [comment]
> This could be an option as there is no way to alter the text, or hide this specific alert as @DocuSignEric mentioned.

Hiding it works for my use case. Closing this issue for now.
