### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by dmarcato** [docusign/native-ios-sdk#16]
Is there any particular reason why bitcode is turned off? Would it be possible to have it enabled? I can't use this SDK in my app if bitcode is off...

**Comment by iOSSDK-DocuSign** [comment]
@dmarcato , We are working on to get this resolved in future. For now, the current SDK version (v2.1.4), has a dependency that doesn't support bitcode fully. 

It's on our roadmap, could you please share more information about your use-cases? Understanding your use-case would help us prioritize it.

**Comment by maslovsa** [comment]
@iOSSDK-DocuSign 
https://monosnap.com/file/3ob33HEMTXYrDVMUoOIQAvUtU3dAXc

**Comment by maslovsa** [comment]
@iOSSDK-DocuSign 
plz take a look on issue from App Store Connect

**ITMS-90381: Too many symbol files**

This issue connects with Bitcode using

**Comment by thomas-dang** [comment]
Hi @maslovsa,

Thank you for the heads up. We'll take a look at this, and get back to you.

Thanks.

**Comment by bencallis** [comment]
Is there any update on this? We are considering using Docusign in a financial app I am working on but the lack of Bitcode support is a major drawback.
