### ISSUE TITLE
login(withAccessToken:) throwing unauthorised error for passing nil to refreshToken and expiresIn optional parameters.

### ISSUE THREAD

**Issue by rakshithn96** [docusign/native-ios-sdk#167]
Our backend uses the JWT Grant because we perform a single login for all users in our DocuSign integration. Since we are not using OAuth, a refresh token is not available. In version 3.1.0, new parameters `refreshToken` and `expiresIn` were added. When I pass nil to these parameters, the DocuSign framework returns an `unauthorized` error. Are these parameters mandatory, or can someone provide more information on how to resolve this issue?

**Comment by ashokds** [comment]
Hi @rakshithn96 : 

We are looking into this and will add an update. Meanwhile, putting this as a reference, the updated sample app which has the login-flow details are present here: https://github.com/docusign/sample-app-tgk-financial-ios/

Details on the `refreshToken` & `expiresIn` usage is linked here: https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/log-in/

Thanks for adding details.

**Comment by ashokds** [comment]
Hi @rakshithn96 : 

Are you migrating your app from an old DocuSignSDK version to a new one? 

Could you please share the current code snippet for the SDK call that results in the `unauthorized` error and the network log. It would be helpful to quickly resolve it. 

Thanks.

**Comment by rakshithn96** [comment]
Hi @ashokds 

I'm trying to upgrade the Docusign from 3.0.3 to 3.2.0. The Xcode version is 15.2. I am using the default login function to login to the DocuSign framework. 

About the network calls. Like 3.0.3 the 3.2.0 version does not initiate any network calls.

Login is done as below with 3.2.0 with 2 new parameters `refreshToken` and `expiresIn`: 

```  
      DSMManager.login(withAccessToken: accessToken, accountId: accountId, userId: userId, userName: userName, email: email, host: hostUrl, integratorKey: integratorKey, refreshToken: nil, expiresIn: nil) { [weak self] _, error in
            if let error = error {
                dLog(logType: .docusign, "Docusign login error: \(error)")
                return
            }
        }

Thanks.

**Comment by ashokds** [comment]
Hi @rakshithn96 : 

Would it be possible to post the steps you use to get the AccessToken and network logs around it. We could schedule a debug session with your team - could you please send the details and your availability to `Mobile Feedback <mobilefeedback [at] docusign.com>` (replace [at] with @) and we'll follow up. 

Thanks for your patience and help so far,

**Comment by mmohareb** [comment]
can you confirm you followed this step 2 in the project setup?
https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/log-in/
![image](https://github.com/user-attachments/assets/70d51dc0-76da-4c11-9b1a-8caa8b7af651)

**Comment by bhagwat8024** [comment]
@mmohareb  , sure we will add this but where can we get refreshToken , is it stored in SDK or we get it in response of OAuth Token

**Comment by mmohareb** [comment]
Refresh token can be nil in your case since you are not using oAuth.

**Comment by depushpendra** [comment]
@mmohareb  do we need to add step 2 in Info.plist even when we are JWTTOken?

**Comment by mmohareb** [comment]
Yes this step is mandatory regardless of the way you authenticate the SDK

**Comment by depushpendra** [comment]
Thanks we will add it but could be possible cause of login(withAccessToken:) throwing unauthorised error for passing nil to refreshToken and expiresIn optional parameters ? Even if we use valid token

**Comment by mmohareb** [comment]
Missing this step will surely cause the unauthorized issue as without this the SDK can’t access the keychain to store the authentication key(either oauth or jwt grant)

The refresh token is an optional parameter that would allow the SDK to refresh the access token after expiry if oauth is being used. So sending nil should not cause this issue.

**Comment by depushpendra** [comment]
Thanks @mmohareb  We will try by adding above step and check. I will let you know incase I will need anymore help.

👍👍👍

**Comment by bhagwat8024** [comment]
@mmohareb  
After updating the info.plist, there are no callbacks (success or error) received during the login process using DSMManager.login
Here is the code snippet we use for login
DSMManager.login(
    withAccessToken: token,
    accountId: config.accountId,
    userId: config.userId,
    userName: config.userName,
    email: config.email,
    host: url,
    integratorKey: config.integrationKey,
    refreshToken: nil,
    expiresIn: nil
) { (account, error) in
    DispatchQueue.main.async {
        if let account = account, error == nil {
            completion(.success(account))
        } else if let error = error {
            completion(.failure(error))
        } else {
            completion(.failure(
                ConnectError.appLevelError(
                    error: ErrorMetadata(errorMessage: "DocuSign login failed",
                                         response: "DocuSign login failed, accessToken: " + token),
                    isLocal: true
                ))
            )
        }
    }
}

**Comment by bhagwat8024** [comment]
@mmohareb 
After updating the info.plist, there are no callbacks (success or error) received during the login process using DSMManager.login.
Here is the code snippet we use for login

```
DSMManager.login(
    withAccessToken: token,
    accountId: config.accountId,
    userId: config.userId,
    userName: config.userName,
    email: config.email,
    host: url,
    integratorKey: config.integrationKey,
    refreshToken: nil,
    expiresIn: nil
) { (account, error) in
    DispatchQueue.main.async {
        if let account = account, error == nil {
            completion(.success(account))
        } else if let error = error {
            completion(.failure(error))
        } else {
            completion(.failure(
                ConnectError.appLevelError(
                    error: ErrorMetadata(errorMessage: "DocuSign login failed",
                                         response: "DocuSign login failed, accessToken: " + token),
                    isLocal: true
                ))
            )
        }
    }
}
```

**Comment by mmohareb** [comment]
@bhagwat8024 is it possible to share a complete log from your app on docusignmobilesdk@docusign.com? if needed we can setup a working session to support you with your integration

**Comment by bhagwat8024** [comment]
@mmohareb 
Yes, we can have a working session tomorrow to support the integration.
Please let me know your availability for the session.

**Comment by mmohareb** [comment]
@bhagwat8024 please reach out to the email mentioned above to arrange this session.

**Comment by mmohareb** [comment]
Thanks @bhagwat8024 and @depushpendra 
To fix the issue with no callbacks for login method, you need to pass the expiresIn parameter for the lifetime of the token.
The refresh token can stay nil and should not cause issues.
Let me know if this works for your scenario, and we will work on updating the docs and handling this better with our next release.

**Comment by mmohareb** [comment]
@rakshithn96 please update us if this issue is still happening for you too?
