### ISSUE TITLE
Request for Documentation or Sample Application for Online Signing Process for IOS

### ISSUE THREAD

**Issue by bhagwat8024** [docusign/native-ios-sdk#168]
We are currently utilizing the DocuSign iOS SDK for offline signing purposes in our application. We are now exploring the possibility of transitioning to an online signing process to enhance the user experience and improve our workflow efficiency.

Could you please confirm if the DocuSign iOS SDK supports the online signing process? If it does, we would appreciate it if you could provide detailed documentation or a sample application that demonstrates the implementation of the online signing process.

current sample app only demonstrate offline signing process.
https://github.com/docusign/sample-app-tgk-financial-ios/

@ashokds  appreciate your help here.

Thank you.

**Comment by InbarGazit** [comment]
https://developers.docusign.com/docs/mobile-sdks/ios-sdk/how-to/request-signature-embedded/ has details about how to do that, can you please try to follow this article and if you run into issue - let us know?

**Comment by mmohareb** [comment]
Hello @bhagwat8024 
if you only require signing online, this is supported using this method [here](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmenvelopesmanager/presentsigningwithpresentingcontroller:envelopeid:animated:completion:)
Let me know if you have issues using this method and we would love to help

**Comment by bhagwat8024** [comment]
@mmohareb  We have implemented the method you suggested. However, we are encountering an issue: whenever this function is called, the signing template appears for one second and then the **DSMSigningCompletedNotification** is triggered.

**Comment by mmohareb** [comment]
@bhagwat8024 can you share a sample project so we can look into this issue? you can use this email alias 

docusignmobilesdk@docusign.com

This is usually an authentication problem, meaning that the logged in user on the SDK doesn't have access to the envelope being signed, causing the view to dismiss right away.
Let us know if this does not help we are happy to help.

**Comment by bhagwat8024** [comment]
@mmohareb  

I have two queries regarding DocuSign integration in our iOS application:

1. Our backend provides only the template ID and the data that needs to be filled into the tabs. Is there a function in the iOS SDK that allows us to pass the template ID and the tab data for online signing?

2. In our Android application, we use the function **createEnvelopeAndLaunchOnlineSigning()** for online signing. Is there a parallel function in the iOS SDK that offers similar functionality?

**Comment by mmohareb** [comment]
Hello @bhagwat8024 
you can check out this [method](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmtemplatesmanager/presentsendtemplatecontrollerwithtemplatewithid:envelopedefaults:pdftoinsert:insertatposition:signingmode:presentingcontroller:animated:completion:)

This allows you to send and start signing a template, and also pass tab data as part of the [`DSMEnvelopeDefaults`  ](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmenvelopedefaults/) parameter
