### ISSUE TITLE
Issue with presentSendTemplateControllerWithTemplateWithId Function - INVALID_RECIPIENT_ID Error

### ISSUE THREAD

**Issue by bhagwat8024** [docusign/native-ios-sdk#169]
I am writing to report an issue we have encountered with the **presentSendTemplateControllerWithTemplateWithId** function, which takes envelopeDefaults as a parameter. Specifically, within envelopeDefaults, there is a recipientDefault that have both recipientId and recipientRoleName.

Our expectation was that the function should work correctly by specifying the role only. However, when we omit the Id, we receive an INVALID_RECIPIENT_ID error. According to the documentation and our understanding, the function should be able to handle cases where only the role is provided.

**Comment by mmohareb** [comment]
hello @bhagwat8024 
if you want to use the role name to identify the recipient then you have to set the property [`recipientselectortype`](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmrecipientdefault/recipientselectortype) to [DSMEnvelopeDefaultsUniqueRecipientSelectorTypeRecipientRoleName
](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmenvelopedefaultsuniquerecipientselectortype/dsmenvelopedefaultsuniquerecipientselectortyperecipientrolename)

Let me know if this solves this issue for you

**Comment by bhagwat8024** [comment]
Yes , it working fine 
Thanks @mmohareb
