### ISSUE TITLE
Receiving CFBundleExecutable Key Error When Submitting App To AppStore

### ISSUE THREAD

**Issue by frankftsai** [docusign/native-ios-sdk#22]
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/AcelityPatientApp.app/Frameworks/DocuSignSDK.framework/Tools.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Docusign SDK Version : 2.2
Docusign SDK source url : https://github.com/docusign/native-ios-sdk

**Comment by jrodriguez-tera** [comment]
Same problem here, any updates coming soon?

**Comment by thomas-dang** [comment]
Hi @jrodriguez-tera,

We resolved some of the App Store upload errors as part of the SDK 2.2.1 and 2.2.2 releases. Could you please confirm which version of the SDK you are on, and if it is the ITMS-90535 / ITMS-90535 error code you are seeing or a different one?

Thanks.

**Comment by jrodriguez-tera** [comment]
Hi @thomas-dang ,

I'm really sorry, after updating the pod version to '2.2.3' it stopped happening, now I'm experiencing the following issue: **ITMS-90809** you'll find more details here: #26 

I guess you can close this one. Thank you and apologies again.

**Comment by thomas-dang** [comment]
Hi @jrodriguez-tera,

Not a problem. For the upload error regarding the UIWebView, we are working on a release to fix that in our SDK and should have it out by next week at the latest.

Thanks.

**Comment by jrodriguez-tera** [comment]
Sounds great, thanks @thomas-dang . Looking forward to receive the update

**Comment by rdougan** [comment]
This appears to be broken again in the latest release. Reverting to `2.2.3` resolves the issue. I'm using CocoaPods.

**Comment by ashokds** [comment]
Hi @rdougan ,

Please add the details on the error you are facing with `v2.3.5`, a screenshot or error-description would be helpful to debug this further and unblock you.

We found that the `Tools.Bundle Info.plist` for `v2.3.5` doesn't have the `CFBundleExecutable` entry. It was removed to patch the original issue found with `v2.2`.

Thanks for reporting!

**Comment by ashokds** [comment]
@rdougan , 

Would you be able to submit the error details to help us reproduce it at our end? 
Also, are you submitting a new app or an update to an existing app?

Thanks.
