### ISSUE TITLE
Template has unsupported Recipient attributes

### ISSUE THREAD

**Issue by PradeshKumar** [docusign/native-ios-sdk#30]
Hi, I'm facing a problem, if I didn't add a recipient name and email-Id, while creating a template.
<img width="869" alt="Untitled" src="https://user-images.githubusercontent.com/1768432/83189331-b2f2d080-a14e-11ea-86a1-4b5c06b9fc8b.png">

Then, when I tried to download the template from an iOS mobile app, I'm getting, **"Template has unsupported Recipient attributes."**. Whether, it's mandatory to add the recipient name and email-Id, while creating the template? Also, if it's mandatory, can't I use any other email-Id apart from the DocuSign account email-Id?

**Comment by thomas-dang** [comment]
Hi @PradeshKumar,

It is generally ok to specify just a role name on the template, and then populate the name and e-mail only at the time of using the template.

The "Template has unsupported Recipient attributes" error may come up if any of the recipients on your template (or the template itself) have been configured to use any of the following recipient features. It also depends on whether you are trying to use the template through our SDK in online mode or offline mode.

**Online Mode Unsupported Recipient Features**

- Signature providers
- Signing groups

**Offline Mode Unsupported Recipient Features**

- Signature providers
- Signing groups
- Access codes
- Additional authentication checks (e.g. phone, SMS)
- Document visibility
- Sign in each location
- Paper signing required
- Signer certificate required
- Notary signer type

Most of these features should be verifiable in our web portal when editing the template recipients. You may have to drill down into the advanced settings at the recipient level or at the template level from that screen.

If you do see any of the features above enabled on your template, you may try disabling them and trying to use the template again through our SDK.

Thanks.

**Comment by PradeshKumar** [comment]
Thanks thomas-dang
