### ISSUE TITLE
Couldn't able to change the navigationBar title color

### ISSUE THREAD

**Issue by PradeshKumar** [docusign/native-ios-sdk#33]
Currently, it's appearing white color and also, all letters are in caps.

`DSMAppearance.setNavigationBarTitleTextFont(UIFont(name: "Cairo", size: 10)!, color: .black)`

**Comment by ashokds** [comment]
Please try with iOS specific font. ("Cairo" is an Android/Google platform font).

Swift: 
`DSMAppearance.setNavigationBarTitleTextFont(UIFont.systemFont(ofSize: 10, weight: UIFont.Weight.bold), color: .black)
`

Objective-c:
`[DSMAppearance setNavigationBarTitleTextFont:[UIFont systemFontOfSize:10 weight:UIFontWeightBold] color:UIColor.systemPinkColor];`

**Comment by ashokmentor** [comment]
Could you please post the code snippet surrounding the call `DSMAppearance.setNavigationBarTitleTextFont` in your project.

One ideal place to invoke this method would be before presenting the signing ceremony. For example, in [DocuSignViewController in swift sample app](https://github.com/docusign/native-ios-sdk/blob/master/docusign-sdk-sample-swift/docusign-sdk-sample-swift/Controllers/DocuSignViewController.swift) can be modified as:  

```
       // set sdk styling
        DSMAppearance.setNavigationBarTintColor(UIColor(red: 46.0/255, green: 109.0/255, blue: 164.0/255, alpha: 1.0))
        DSMAppearance.setBarButtonItemsTintColor(UIColor.white)
        DSMAppearance.setNavigationBarTitleTextFont(UIFont.systemFont(ofSize: 10, weight: UIFont.Weight.bold), color: .green)

        let templateId: String = ProfileManager.sharedInstance.getCurrentTemplateId()
        let tabData: Dictionary = ProfileManager.sharedInstance.getTemplateTabData(templateId:templateId)
        let recipientData: Array = ProfileManager.sharedInstance.getTemplateRecipientData(templateId:templateId)
        let onlineSign: Bool = !ProfileManager.sharedInstance.getUseOfflineFlow()
        let attachmentUrl: URL? = ProfileManager.sharedInstance.getAttachmentUrl()
        let customFields = ProfileManager.sharedInstance.getCustomFieldsData(templateId:templateId)

        // display template via sdk
        TemplatesManager.sharedInstance.displayTemplateForSignature(templateId: templateId, controller: self, tabData: tabData, recipientData: recipientData, customFields:customFields, onlineSign: onlineSign, attachmentUrl: attachmentUrl) { (controller, errMsg) in
```

And for the signer named "The Lion King", resulting navigation bar during Signing would look like:
![Issue-33-github](https://user-images.githubusercontent.com/63634906/83821875-65adbc00-a684-11ea-946a-9c30d3be8055.png)

**Comment by ashokds** [comment]
Could you please post the code snippet surrounding the call `DSMAppearance.setNavigationBarTitleTextFont` in your project.

One ideal place to invoke this method would be before presenting the signing ceremony. For example, in [DocuSignViewController in swift sample app](https://github.com/docusign/native-ios-sdk/blob/master/docusign-sdk-sample-swift/docusign-sdk-sample-swift/Controllers/DocuSignViewController.swift) can be modified as:  

```
       // set sdk styling
        DSMAppearance.setNavigationBarTintColor(UIColor(red: 46.0/255, green: 109.0/255, blue: 164.0/255, alpha: 1.0))
        DSMAppearance.setBarButtonItemsTintColor(UIColor.white)
        DSMAppearance.setNavigationBarTitleTextFont(UIFont.systemFont(ofSize: 10, weight: UIFont.Weight.bold), color: .green)

        let templateId: String = ProfileManager.sharedInstance.getCurrentTemplateId()
        let tabData: Dictionary = ProfileManager.sharedInstance.getTemplateTabData(templateId:templateId)
        let recipientData: Array = ProfileManager.sharedInstance.getTemplateRecipientData(templateId:templateId)
        let onlineSign: Bool = !ProfileManager.sharedInstance.getUseOfflineFlow()
        let attachmentUrl: URL? = ProfileManager.sharedInstance.getAttachmentUrl()
        let customFields = ProfileManager.sharedInstance.getCustomFieldsData(templateId:templateId)

        // display template via sdk
        TemplatesManager.sharedInstance.displayTemplateForSignature(templateId: templateId, controller: self, tabData: tabData, recipientData: recipientData, customFields:customFields, onlineSign: onlineSign, attachmentUrl: attachmentUrl) { (controller, errMsg) in
```

And for the signer named "The Lion King", resulting navigation bar during Signing would look like:
![Issue-33-github](https://user-images.githubusercontent.com/63634906/83821875-65adbc00-a684-11ea-946a-9c30d3be8055.png)

**Comment by PradeshKumar** [comment]
Hi @ashokds,

I think, you're trying in an offline mode. Please check it in on online mode:

<img width="376" alt="navigationBarTitleIssue" src="https://user-images.githubusercontent.com/1768432/83841950-7fe8a800-a71f-11ea-8e9e-8c5d2cf1dea5.png">

**Note:** I'm using DocuSign SDK v2.2.5

**Comment by PradeshKumar** [comment]
Any update @ashokds ?

**Comment by LarryKlugerDS** [comment]
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.
