### ISSUE TITLE
DocuSign is always adopting an existing signature in an online mode

### ISSUE THREAD

**Issue by PradeshKumar** [docusign/native-ios-sdk#34]
Hi, I want to adopt "Draw your signature" every time, whenever a user try to perform a DocuSign in an online mode. Even, I've tried signature adoption "Start on draw" and  "Enable draw new signature for each signature or initial field". But, no luck... 

Also, why I'm getting a black shadow like below, whenever I'm loading a template:
<img width="501" alt="blackShadow" src="https://user-images.githubusercontent.com/1768432/83668443-9858a580-a5ed-11ea-898c-0e0a1951f650.png">

**Comment by ashokds** [comment]
Hi @PradeshKumar ,

Could you please post the details on the signers included in your template, or if attaching the entire template that would be helpful. 

For offline Signing, SDK will always ask the signer to adopt a fresh signature for in-person or remote signers. You are using `Offline Signing`, right? 

For online Signing, the behaviour differs based on the signer type (in-person vs remote) and account settings.

**Comment by PradeshKumar** [comment]
Thanks @ashokds.

PFB the details of the signers:

```
let recipientDatum = DSMRecipientDefault()
recipientDatum.recipientRoleName = "wsoffer"
recipientDatum.recipientSelectorType = .recipientRoleName
recipientDatum.recipientType = .inPersonSigner
recipientDatum.inPersonSignerName = "Pradesh"
recipientDatum.recipientEmail = Configuration.sharedInstance.docuSignUserId
recipientDatum.recipientName = "xxxxxxxxxx"

let recipientDatum1 = DSMRecipientDefault()
recipientDatum1.recipientRoleName = "wsoffer2"
recipientDatum1.recipientSelectorType = .recipientRoleName
recipientDatum1.recipientType = .CC
recipientDatum1.recipientEmail = "xxxxxxx"
recipientDatum1.recipientName = "Pradesh V"

let envelopeDefaults = DSMEnvelopeDefaults()
envelopeDefaults.recipientDefaults = [recipientDatum1, recipientDatum]
```

Can't, I achieve using the following settings for a remote signer to adopt a fresh signature every time?

<img width="704" alt="signingSetting" src="https://user-images.githubusercontent.com/1768432/83694010-cdc4b980-a614-11ea-83c3-2fdcf9005b59.png">

Also, is there a way to change the activity indicator label message? and why, I'm getting a black shadow, whenever I'm loading a template?

**Comment by LarryKlugerDS** [comment]
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.
