### ISSUE TITLE
presentSendTemplateControllerWithTemplateWithId not loading/displaying our template after switching to token login with loginWithAccessToken()

### ISSUE THREAD

**Issue by cbrian** [docusign/native-ios-sdk#42]
Our DocuSign In-App flow needs to be logined with access token instead of account id and pwd for better security.    So, we’re now switching to your loginWithAccessToken api from already working loginWithEmail api for embeded/inperson app signing flow .  
 
Even though we got  loginWithAccessToken api to work with the access token from, https://developers.docusign.com/oauth-token-generator?, on user authentication as shown below from your SDK provided sample,  we can no longer see any template downloading into our app when calling the presentSendTemplateControllerWithTemplateWithId api below.   It appears that loginWithAccessToken api changed  in-person signing to remote signing as we’re now getting its email invite to complete signing instead.
 
Is the above template loading problem a known issue with logined access token when using native iOS SDK?  How do we configure the same presentSendTemplateControllerWithTemplateWithId call in your sdk sample  properly to show template in our app successfully when logined with loginWithAccessToken?

// Related code changes from DocuSign SDK sample, docusign-sdk-sample-objc,
 NSURL *turl = [NSURL URLWithString:@"https://demo.docusign.net/restapi"];        
        // log user into docusign api
#if SupportLoginEmail // Working  
        [DSMManager loginWithEmail:@"bcao@x.com" password:@"{hidepwd}" integratorKey:@"{integratorKey}" host:turl completion:^(DSMAccountInfo *accountInfo, NSError *error)
#else
        [DSMManager loginWithAccessToken:@"{AccessToken}"
                               accountId:@"{account id}"
                                  userId:@"{userId}"
                                userName:@"bcao@x.com"
                                   email:@"bcao@x.com"
                                    host:turl
                           integratorKey:@"{integratorKey}"
                              completion:^(DSMAccountInfo *accountInfo, NSError *error)
#endif {
                if (error != nil) {
                    NSLog(@"An error occurred attempting to log into DocuSign: %@", error);
                    //[ProgressHUD dismiss];                 
                }
                else {
                    NSLog(@"User Authenticated"); // Both logins reached here
  }….
 
 
……. // Problem: Template no longer loaded/displayed with api below after loginWithAccessToken api 
 
[self.mDSMTemplatesManager
     presentSendTemplateControllerWithTemplateWithId:@"8638fb2a-2a85-4c4e-8f1e-a9e64e37b340"
     envelopeDefaults:envelopeDefauts
 
  pdfToInsert:attachmentData
     insertAtPosition:DSMDocumentInsertAtPositionEnd
     signingMode:(!useOffline) ? DSMSigningModeOnline :DSMSigningModeOffline
     presentingController:controller
     animated:YES
     completion:^(UIViewController *viewController, NSError *error) {
        if (error)
        {
            NSLog(@"%@", error);
        }
    }];
 
Please help soon on this urgent api issue with your iOS native SDK api, presentSendTemplateControllerWithTemplateWithId.

**Comment by thomas-dang** [comment]
Hi @cbrian,

Thank you for reaching out. Our team is taking a look, and we will get back to you.

Thanks.

**Comment by KDP0123456** [comment]
We found the problem, if we sign in with token and add the code below to our file, then the signing view(In-person) will not show up. Could you guys please help us with this?

```
NSMutableArray *recipientDefaults = [NSMutableArray arrayWithCapacity:1];
DSMRecipientDefault *recipientIPS1 = [[DSMRecipientDefault alloc] init];
    recipientIPS1.recipientRoleName = @"";
    recipientIPS1.recipientSelectorType = DSMEnvelopeDefaultsUniqueRecipientSelectorTypeRecipientRoleName;
    recipientIPS1.recipientType = DSMRecipientTypeInPersonSigner;
    recipientIPS1.inPersonSignerName = @"";
    recipientIPS1.recipientName = @"";
    recipientIPS1.recipientEmail = @"";
    [recipientDefaults addObject:recipientIPS1];
    return [recipientDefaults copy];
```

**Comment by ashokds** [comment]
Hi @cbrian ,

Thanks for adding additional details related to `recipientDefaults`. Please do make sure that the `roleName` and other other values match exactly for `@"8638fb2a-2a85-4c4e-8f1e-a9e64e37b340"` template in your test account. 

```
    recipientIPS1.recipientRoleName = @""; // --> RoleName on template
    recipientIPS1.inPersonSignerName = @""; // --> Custom IPS name
    recipientIPS1.recipientName = @""; // --> Name matching the authenticated account name (host)
    recipientIPS1.recipientEmail = @""; // --> Email matching the authenticated account email (host)
```


Also, if these details don't match with the host account (account that is currently authenticated with SDK), SDK would create the envelope and immediately set the status to be "sent". Depending on the signing mode (online vs offline) used, SDK would send the `DSMSigningCompletedNotification` or `DSMEnvelopeCachedNotification` notifications. In case of any error, for example if unsupported tab types added to template, SDK sends `DSMSigningCancelledNotification` for online signing. Please note that all of these notifications have `userInfo` object that contains the `envelopeId` or `templateId`, please add this detail if you are getting such failures. [reference: Notification Codes](https://github.com/docusign/native-ios-sdk/blob/master/DocuSignSDK.framework/Headers/DSMNotificationCodes.h)


Note: Many aspects of SDK are configurable and it's worth taking a look at [SetupConstants](https://github.com/docusign/native-ios-sdk/blob/master/DocuSignSDK.framework/Headers/DSMSetupConstants.h). For example, SDK performs strict match for roleName and other properties in accordance with the DocuSign API. One of the setupConstants: `DSM_SETUP_RECIPIENT_DEFAULTS_CASE_INSENSITIVELY_MATCH_ROLE_NAME` allows to override strict matching for `roleNames`. 

Thank you!

**Comment by KDP0123456** [comment]
Hi @ashokds,

Thank you so much for your time to answer our questions.
All the values exactly matches the template, and the code works perfectly with `DSMManager loginWithEmail`, but `loginWithAccessToken`

**Comment by KDP0123456** [comment]
And completion returns no errors
```
presentSendTemplateControllerWithTemplateWithId:(NSString *)templateId
                                       envelopeDefaults:(nullable DSMEnvelopeDefaults *)envelopeDefaults
                                            pdfToInsert:(nullable NSData *)pdfToInsert
                                       insertAtPosition:(DSMDocumentInsertAtPosition)insertAtPosition
                                            signingMode:(DSMSigningMode)signingMode
                                   presentingController:(UIViewController *)presentingController
                                               animated:(BOOL)animated
                                             completion:(nullable void(^)(UIViewController *_Nullable viewController, NSError *_Nullable error))completion;
```

**Comment by cbrian** [comment]
Hi Ashok,  KDP was very right earlier that we are seeing a very critical native SDK api issue instead of just a configuration issue now.  The OAuth login call, loginWithAccessToken, isn't supposed to affect your SDK template api as this presentSendTemplateControllerWithTemplateWithId call as Matt suggested.   But, we're definitely seeing it changing the DocuSign template behavior from In-Person/Embeded flow to the unintended Remote-signer email just by switched the login call from loginWithEmail() to loginWithAccessToken().   

This issue can be reproduced using your provided SDK sample with recipientIPS1 initialization code added as above and you'll see a blank screen instead of template content after selecting the same Online mode at the begining of a DocuSign flow.    DocuSign native SDK api bug is now affecting our release schedule and we're not happy with the lack of good dev support on resolving our reported DocuSign SDK issues in spite of subscribing your highest premier service.   Is there anyway that we can get faster and helpful response to resolve the DocuSign SDK api issue?  Thanks for your help.

**Comment by thomas-dang** [comment]
Hi @cbrian / @KDP0123456,

Just one quick confirmation. Does the `userName` and `email` values you pass in to `loginWithAccessToken` match the `recipientName` and `recipientEmail` you set on the `DSMRecipientDefault` object you pass in to `presentSendTemplateControllerWithTemplateWithId`? At minimum, those must match for our SDK to display the signing view for the template.

Also, when you do have the issue when calling `presentSendTemplateControllerWithTemplateWithId`, are you immediately receiving the `DSMSigningCompletedNotification` NSNotificationCenter event from our SDK?

It might be easier if we set up a call / screen share to debug the issue with you. Would you mind sending a quick e-mail to iOSSDK@docusign.com including a link to this issue, and then we can coordinate on a meeting time?

Thanks.

**Comment by cbrian** [comment]
> Hi @cbrian / @KDP0123456,
> 
> Do the `userName` and `email` values you pass in to `loginWithAccessToken` match the `recipientName` and `recipientEmail` you set on the `DSMRecipientDefault` object you pass in to `presentSendTemplateControllerWithTemplateWithId`? At minimum, those must match for our SDK to display the signing view for the template.
> 
> Also, when you do have the issue when calling `presentSendTemplateControllerWithTemplateWithId`, are you immediately receiving the `DSMSigningCompletedNotification` NSNotificationCenter event from our SDK?
> 
> It might be easier if we set up a call / screen share to debug the issue with you. Would you mind sending a quick e-mail to [iOSSDK@docusign.com](mailto:iOSSDK@docusign.com) including a link to this issue, and then we can coordinate on a meeting time?
> 
> Thanks.

**Comment by cbrian** [comment]
> > Hi @cbrian / @KDP0123456,
> > Do the `userName` and `email` values you pass in to `loginWithAccessToken` match the `recipientName` and `recipientEmail` you set on the `DSMRecipientDefault` object you pass in to `presentSendTemplateControllerWithTemplateWithId`? At minimum, those must match for our SDK to display the signing view for the template.
> > Also, when you do have the issue when calling `presentSendTemplateControllerWithTemplateWithId`, are you immediately receiving the `DSMSigningCompletedNotification` NSNotificationCenter event from our SDK?
> > It might be easier if we set up a call / screen share to debug the issue with you. Would you mind sending a quick e-mail to [iOSSDK@docusign.com](mailto:iOSSDK@docusign.com) including a link to this issue, and then we can coordinate on a meeting time?
> > Thanks.

Will do right away and thanks so much for getting back early this time.

**Comment by thomas-dang** [comment]
Hi @cbrian,

Sounds good.

I do recommend doing a quick check to confirm the following though (as I did notice some mismatch in the originally-posted code that might be causing the issue):

> Do the `userName` and `email` values you pass in to `loginWithAccessToken` match the `recipientName` and `recipientEmail` you set on the `DSMRecipientDefault` object you pass in to `presentSendTemplateControllerWithTemplateWithId`? At minimum, those must match for our SDK to display the signing view for the template.

Thanks.

**Comment by cbrian** [comment]
> [iOSSDK@docusign.com](mailto:iOSSDK@docusign.com)

Hi Thomas, just emailed twice to iOSSDK@docusign.com and got it bounced back.  Do you have another email that we can contact you directly?

**Comment by cbrian** [comment]
> Hi @cbrian / @KDP0123456,
> 
> Do the `userName` and `email` values you pass in to `loginWithAccessToken` match the `recipientName` and `recipientEmail` you set on the `DSMRecipientDefault` object you pass in to `presentSendTemplateControllerWithTemplateWithId`? At minimum, those must match for our SDK to display the signing view for the template.
> 
> Also, when you do have the issue when calling `presentSendTemplateControllerWithTemplateWithId`, are you immediately receiving the `DSMSigningCompletedNotification` NSNotificationCenter event from our SDK?
> 
> It might be easier if we set up a call / screen share to debug the issue with you. Would you mind sending a quick e-mail to [iOSSDK@docusign.com](mailto:iOSSDK@docusign.com) including a link to this issue, and then we can coordinate on a meeting time?
> 
> Thanks.

Thanks Thomas so much for the great help earlier and please update us with your findings on our other inquiries later.
