### ISSUE TITLE
Docusign iOS SDK integration issue in custom flow(in integrating own backend and docusign iOS SDK)

### ISSUE THREAD

**Issue by akshays-sdei** [docusign/native-ios-sdk#44]
We have our own app where we are integrating Doucsign iOS SDK,
What we are doing.
We are uploading PDFs from backend using Docusign API, and then this uploaded PDF needs to be opened in iOS App, using Docusign SDK.
For that we are using iOS SDK call, 

```
func displayTemplateForSignature(templateId: String, controller: UIViewController, tabData: Dictionary<String, String>, recipientData: Array<DSMRecipientDefault>, customFields:DSMCustomFields?, onlineSign: Bool, attachmentUrl: URL?, completionHandler: @escaping ((UIViewController?, Error?) -> Void))
```

but we are unable to load the PDF using template id, it also needs recipient data, but we are not adding recipient data while uploading the PDF(template) still it is asking for recipient data in iOS SDK,
If we send some data in recipient data in iOS SDK then it either gives error or dosen't do anything.
The error it gives is

```
2020-08-07 15:30:00.063586+0530 Public Adjuster[8759:2454775] Error encountered during signing: Template has invalid recipient(s) associated with roleName: signer. Current Setup config for DSM_SETUP_RECIPIENT_DEFAULTS_CASE_INSENSITIVELY_MATCH_ROLE_NAME : false
2020-08-07 15:30:00.063945+0530 Public Adjuster[8759:2454775] Warning: Encountered `nil view` during signing
```

Sometime it gives this error
```
DSM_SETUP_RECIPIENT_DEFAULTS_CASE_INSENSITIVELY_MATCH_ROLE_NAME allows to override strict matching for roleNames.
```
Also i want to know that do we get envelope ID after the PDF is signed and sent, as i didnt see any method where it return the envelope ID in iOS SDK.

Any help will be appreciated, already talked with docusign support team and they asked to post our queries here on stackoverflow.

**Comment by ashokds** [comment]
Original questions over stackoverflow:

- https://stackoverflow.com/questions/63312170/docusign-ios-sdk-integration-issue-in-custom-flowin-integrating-own-backend-and/63335134#63335134 [Answered over there]

- https://stackoverflow.com/questions/63340118/docusign-ios-sdk-directly-sending-envelope-without-opening-anything-also-not-ask/63345485#63345485 [Currently open question, adding the same details below]

This behaviour, sending the envelope directly, is triggered when DocuSign SDK can not find any signers in the template/envelope that matches the logged-in user. Given that you are using the `recipientDefaults`, ensure that your signer information on the template (preset signer on the DocuSign web) matches the Account information exactly with the `recipientDefaults` object.

You may compare it with [![Accout info accessible via preferences on DocuSign web][1]][1]. 

One issue I noticed is the signer type is set to `need to sign` which corresponds to a `remoteSigner` on the DocuSign web. And on the `recipientDefaults` object it's set as `inPersonSigner`. It should be `.signer` corresponding to `DSMRecipientTypeSigner`.

`recipientDatum.recipientType = .signer`.

Or you may change the `need to sign` to `in person signer` on the DocuSign web.

[![enter image description here][2]][2]

Another suggestion is to remove the `name` & `email` from the template screenshot shared and keep that empty as the client app is passing `name` & `email` with the `recipientDefaults` object to the SDK.


More details: [How to set recipient defaults][3]


  [1]: https://i.stack.imgur.com/KMTI6.png
  [2]: https://i.stack.imgur.com/drJbx.png
  [3]: https://github.com/docusign/native-ios-sdk/issues/43#issuecomment-670092132

**Comment by akshays-sdei** [comment]
I did the changes you asked for,
i was able to open the pdf for signature when i have passed my account credentials which i use to login in docusign as a recipient.
SO the recipient which i am passing should be a docusign user or can i pass any email and name and still open the pdf and take signature.
or the user must be a docusign user to sign the pdf.

**Comment by ashokds** [comment]
Hi @akshays-sdei 

Nice! 

>SO the recipient which i am passing should be a docusign user or can i pass any email and name and still open the pdf and take signature.
> or the user must be a docusign user to sign the pdf.

It depends, what kind of signer it is. 

For "Need to sign" i.e. "Remote Signers":
- Online/Offline signing mode: It must be a DocuSign user to immediately start the signing process on the device using templates. If name/email is added for a non-DocuSign user, SDK would bring the created envelope to "sent" status and send the notification (given no local signers pending); in this case you won't see signing loading with PDF. The person in-turn would receive an email to sign the sent envelope. That person could be new to DocuSign, no prior accounts needed.

For "In Person Signer" (IPS):
- Online/Offline signing mode: User could be added with the name. Host must be a DocuSign user and currently logged in with SDK to initiate the signing. 

Out of curiosity, are you in touch with any of the DocuSign customer support team to get help on signers/template configuration? It would help to get clarity on this by engaging [professional service](https://www.docusign.com/features-and-benefits/services-support).

**Comment by LarryKlugerDS** [comment]
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.
