### ISSUE TITLE
[Question] react-native support

### ISSUE THREAD

**Issue by scheung38** [docusign/native-ios-sdk#45]
Hi I do see native iOS support, but cannot see react-native support, how to query existing sandbox from react-native

**Comment by LarryKlugerDS** [comment]
Hi, 
Unfortunately we don't have a specific SDK for react-native support. 
I'd suggest that you call the API directly as needed. 

What platforms are you targeting for your application? 
Are you building the app for your company, or for a client?
Can you say anything about the use case or purpose of your application?
Thanks,
Larry

**Comment by ashokds** [comment]
Link: https://github.com/docusign/native-ios-sdk/issues/49
