### ISSUE TITLE
Present compose view controller with envelope ID

### ISSUE THREAD

**Issue by augustocollerone** [docusign/native-ios-sdk#50]
Hi!

We are integrating the DocuSign SDK into our native app but we are unable to replicate the experience we currently have on the web witch also integrates DocuSign.

What we would like to accomplish is that the server uploads the files and creates the envelope, then it sends the envelope ID to the app witch goes into the compose screen. This would allow the user to modify, delete or add new tabs in the documents before getting into the signing/sending part of the flow.

Thank you in advance

**Comment by ashokds** [comment]
Hi @augustocollerone ,

This feature is not yet available in the DocuSign iOS SDK. Currently it only allows to start a new envelope with `presentComposeEnvelopeController...` which would present a UI componet to add documents to envelope on the device. 
SDK, as of v2.3.5, doesn't allow resuming a draft with the compose flow.

Are you in touch with any of the Account Specialist or Support Professional who could better assist you with to formally request this feature and add to our roadmap.

Thanks!
