### ISSUE TITLE
Online Mode: Duplicate entries not populating

### ISSUE THREAD

**Issue by mjzandona** [docusign/native-ios-sdk#51]
I have two identical templates, one I use for offline signing and one for online (email) signing.  The offline template works fine.  However, when I use the online template, any tab data that populates over multiple fields shows as blank.  For example, I have a field called customerName in 8 spots throughout my envelope.  None of the fields are populating during the signing ceremony.  Again, the fields populate properly in the offline signing ceremony.

**Comment by mjzandona** [comment]
Oh.  And I was able to confirm this by changing one field to customerName1 and setting my tabData to "customerData1" and then that field was able to populate in online mode.

**Comment by ashokds** [comment]
Hi @mjzandona ,

We'll follow up on this: Why all of the fields with the same name during Online signing aren't getting updated.

Thanks!

**Comment by ashokds** [comment]
@mjzandona : Would it be possible to add the template that's resulting in the behaviour. 

Guide to download template: https://support.docusign.com/en/guides/ndse-user-guide-download-template

**Comment by LarryKlugerDS** [comment]
Closing due to age of last activity. 
Please respond if this is still an issue.
Thank you.
