### ISSUE TITLE
Is tvOS supported in the iOS SDK?

### ISSUE THREAD

**Issue by thepost** [docusign/native-ios-sdk#55]
I'm investigating whether I can use this SDK for my client's TV app, and I saw that these permissions were [required in the plist](https://developers.docusign.com/ios_sdk/developer.html):

- CAMERA: tvOS can access the photos via **PhotoKit**, but it doesn't have a camera ✅❌
- CONTACT: tvOS can't access contacts ❌
- LOCATION: tvOS can access the location via **CoreLocation** ✅

Are these _optional_ in the Docusign SDK, or actually _required_?

**Comment by thomas-dang** [comment]
Hi @thepost,

We currently do not support using our iOS SDK in tvOS apps. However, would you be able to provide additional details on your  desired workflow? That will help us evaluate it for our future roadmap.

Thanks.

**Comment by thepost** [comment]
Thanks. Are there any technical limitations preventing someone from using the **Click API** (with no signature) on tvOS?

Or is it just that you don't support tvOS in the SDK?

**Comment by thepost** [comment]
Great, thanks for confirming. We'll be using the SDK for iOS/iPad too, so I'll have a better idea of the workflow to help you with the roadmap soon. 🙂

**Comment by ashokds** [comment]
Hi @thepost ,

v2.4 is the latest available sdk version. It now supports compose-envelope for programmatically setting documents, signers and tabs for an envelope. 

You may use `pod update 'DocuSign'` to fetch the latest `v2.4` release. 

I'll close this issue, as official support for tvOS is not yet planned for immediate support. 

Thanks.
