### ISSUE TITLE
Programatically set the document and recipients for a new envelope

### ISSUE THREAD

**Issue by paulcirstean-yonder** [docusign/native-ios-sdk#57]
I have recently started to look at the DocuSign native iOS SDK. I am trying to create a new envelope (to be sent via email for signing) by setting the recipients and the documents programatically (not going through the presentComposeEnvelopeController flow which requires users to manually select the files and recipients). 

I can use the DocuSignESign framework (to make direct API calls) but then I'm missing the view controller in which users can add fields (signature, text, date, name, initials etc.) before sending to signing.

How do you recommend to implement this?

**Comment by ashokds** [comment]
Hi @paulcirstean-yonder ,

We recently added this feature and associated release `Native-iOS-SDK v2.4` (currently in beta) is now available for you to try. Details on the implementation are here: [compose envelope guide](https://github.com/docusign/native-ios-sdk/blob/release/2.4/Compose-Envelope.md#v1-compose-envelope---programmatically-beta)


### ChangeLog: [v2.4] - 02/05/2021 - Beta
#### New interface to create envelopes and start signing directly using Compose Envelopes flow with `composeEnvelopeWithEnvelopeDefinition:signingMode:completion` in `DSMEnvelopesManager`.


## Get SDK Framework for v2.4 release beta

[Integration guide with additional details](https://github.com/docusign/native-ios-sdk/blob/release/2.4/support-files/Integration-Troubleshooting.md)

Beta framework can be pulled with CocoaPods by using specific branch `release/2.4`. Here are the steps:
 - Update entry in your podfile to fetch 'DocuSign'
    - pod 'DocuSign', :git => 'https://github.com/docusign/native-ios-sdk.git', :branch => "release/2.4"
 - Install git-lfs via brew: brew install git-lfs
 - Activate git-lfs next: git lfs install
 - Fetch pods : pod install
   - Console Output: Pre-downloading: `DocuSign` from `https://github.com/docusign/native-ios-sdk.git`, branch `release/2.4`


Note: One thing to confirm is if the DocuSignSDK.framework/DocuSignSDK binary downloaded is around 105 MB. If it is not around that size, there may have been some issue with the download and we can try a few approaches to fix it, [additional details](https://github.com/docusign/native-ios-sdk/blob/release/2.4/support-files/Integration-Troubleshooting.md).


Thanks for your question!

**Comment by paulcirstean-yonder** [comment]
Hi @ashokds . Thanks for the quick reply. This is what I'm looking for.

Any idea why I'm getting this exception when I'm trying to initialise a DSMDocumentBuilder: "terminating app due to uncaught exception 'DSMDocumentBuilderException', reason: 'Document Error Occurred'".

This is how I initialize the builder:
let document = DSMDocumentBuilder()
            .addName("UtilityBill")?
            .addDocumentId(1)?
            .addFilePath(Bundle.main.url(forResource: "UtilityBill", withExtension: "pdf")!.absoluteString)?
            .build()

The file path is valid and the document is from the Swift sample app.

**Comment by paulcirstean-yonder** [comment]
Hi @ashokds . I was able to solve the DSMDocumentBuilderException by using Bundle.main.path(forResource:) instead of Bundle.main.url(forResource:). 

I can now create programatically remote envelopes but how can I use the built in DocuSign UI to add fields (signature, text, date, name, initials etc.). Is there a way to do that or should we build our own view controller to add fields and create tabs?

**Comment by ashokds** [comment]
Hi @paulcirstean-yonder , 

👍 

> Is there a way to do that or should we build our own view controller to add fields and create tabs?

As of v2.4 beta, SDK either allows full UI control (i.e. using compose ui to add documents, recipient, email-details and later tabs) or programatic way to define the entire envelope (documents, recipient and tabs along with other details). If the tab details (tab-type, location-on-pdf, tab-dimension, etc) are well known for most of the cases, I would recommend using the TabBuilder to add tabs with programmatic way to directly launch the signing ceremony. 

Is there a DocuSign counterpart you are working with for your integration? It'd help to learn more about your use-case and we would be able to recommend the best path for your app. 

Thanks for the update.

**Comment by ashokds** [comment]
Hi @paulcirstean-yonder ,

v2.4 has been released publicaly. Please use `pod update 'DocuSign'` to get the latest pod. 

Compose Envelope Guide has helpful instructions to get started with programmatically setting the document and recipients for an envelope. 
https://github.com/docusign/native-ios-sdk/blob/v2.4/Compose-Envelope.md 

I'll close this issue. 
Thanks.

**Comment by paulcirstean-yonder** [comment]
Hi @ashokds. Sorry for the delayed response. We just restarted our work on the Docusign integration. We have a native iOS application where we store multiple documents. Our ambition is to select a document from our application and send it to DocuSign. Ideally, we would like to use the already existing UI from the Docusign SDK. Do you know if there are plans to allow for this option in a future release? Also, is there a way to deep link directly to the DocuSign iOS native application? I've noticed  this Docusign deep link (docusignit://) but I don't know how to pass the document that I want to sign.
