### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by allymf** [docusign/native-ios-sdk#62]
I'm working in a project that doesn't use CocoaPods. Do you intend to support Swift Package Manager?

**Comment by ashokds** [comment]
Hi @allymf ,

Swift package manager is pending prioritization on our product roadmap. Are you working with someone on the DocuSign Customer Support team? 

Also, it would help if you could share more details on your use-case (offline signing, templates, etc).

Thanks.

**Comment by bencallis** [comment]
Any update on SPM support?

**Comment by fischu** [comment]
judging by the last comment's date, I'll assume this never became a priority
