### ISSUE TITLE
DocuSign conflict with other pods

### ISSUE THREAD

**Issue by tutucmarin** [docusign/native-ios-sdk#65]
After installing the DocuSign pod, I've got two existing pods not working, the [MessageKit](https://github.com/MessageKit/MessageKit) and [ROX](https://docs.cloudbees.com/docs/cloudbees-feature-management/latest/getting-started/ios-sdk).

**MessageKit** - If calling the `DSMManager.setup()` before showing the MessageKit ViewController, the app crashes with the below error:
`Fatal error: MessageKit: Could not load the color asset.: file MessageKit/UIColor+Extensions.swift, line 32`
**ROX** - The Rox library just stops receiving (fetching) the data from its remote service, without any logs from ROX or DocuSign.

**Comment by ashokds** [comment]
Hi @tutucmarin ,

`DSMManager.setup()` from the `AppDelegate` or any other place (say a view-controller) should be fine as long as it's done before making other sdk calls. There are some `UIColor+Extensions` in iOS SDK, though they shouldn't interfere with any other similar `UIColor` extensions in other pods.

It would be the best to get our hands on a Sample app that successfully reproduces these 2 issues you have mentioned. 

Please create a sample project that reproduces the behavior and attach here to help you. 

Thanks for reaching out.

**Comment by tutucmarin** [comment]
Hi @ashokds!

Thanks for a quick answer.
Here's the sample app - https://github.com/tutucmarin/DocuSign-issue.git

Here are the instructions on how to replicate the issues:

**How to replicate the issue with MessageKit:**

1. Make sure the DocuSign and MessageKit pods are installed
2. In AppDelegate, uncomment line 20 (`DSMManager.setup()`)
3. Run the app

As a result, the app will crash.
If you remove the DocuSign pod, comment on all DocuSign code, and run the app again, everything will work fine.

**How to replicate the issue with ROX:**

1. Make sure the DocuSign and ROX pods are installed
2. Run the app and wait for ROX to fetch the remote the configuration
3. After ROX will fetch the configuration, the value of the "docuSignTest" flag will be printed in the Xcode terminal:

In case when the DocuSign pod is installed, the remote data will never be fetched and we will always get the following output:

```
		FEATURE_FLAG - STATUS: 3 | HAS CHANGES false
		FEATURE_FLAG - VALUE: local_value
		FEATURE_FLAG ================================================
```

In case when the DocuSign pod is not installed, the remote data will be always fetched, and we will always get the following output:
```
		FEATURE_FLAG - STATUS: 3 | HAS CHANGES false
		FEATURE_FLAG - VALUE: remote_value
		FEATURE_FLAG ================================================
```

Thank you!

**Comment by tutucmarin** [comment]
Hi, @ashokds !

Any updates so far?

**Comment by ashokds** [comment]
Hi @tutucmarin , 

Thanks a bunch for uploading the project that reproduces the issues you reported and other relevant details.
We are taking a look and will post update here.

**Comment by ashokds** [comment]
Hi @tutucmarin ,

Regarding the "MessageKit" issue. Noticed that the installed "MessageKit" pod has an asset group `Assets.xcassets` under `Resources` that isn't included in the `MessageKit.framework` target membership. Editing it locally, ended up fixing the error: `Fatal error: MessageKit: Could not load the color asset.: file MessageKit/UIColor+Extensions.swift, line 32`

Here is a screenshot that could help with it.
<img width="1115" alt="MessageKit-Target-Membership" src="https://user-images.githubusercontent.com/17131511/112873587-aee95500-9076-11eb-9a5c-a411001d5889.png">

For `ROX`, I'll try to add helpful details later this week. It looks like independent of the `DocuSign` pod.

Thanks.

**Comment by bharadwaj465** [comment]
@tutucmarin, 

**Regarding the second issue where the Rox framework was not fetching the `remote_value` when DocuSignSDK was integrated:** 

We have manually integrated the framework available [here](https://github.com/docusign/native-ios-sdk/blob/master/DocuSignSDK.zip) to check if there is an issue with the framework and found that `remove_values` are being fetched properly. 

<img width="1680" alt="Rox pod issue" src="https://user-images.githubusercontent.com/9475547/114469303-b85bdc80-9ba1-11eb-856d-03804070c1e6.png">

We believe this issue was independent of DocuSignSDK. We are unsure how their values are fetched.

**Comment by bharadwaj465** [comment]
To manually integrate our SDK, please find the steps [here](https://developers.docusign.com/docs/ios-sdk/developer.html). Go to `Integrations` tab.
