### ISSUE TITLE
Display a template with DS EU Advanced with SMS

### ISSUE THREAD

**Issue by soufianeEssabbane** [docusign/native-ios-sdk#67]
Hi, 

Can you please assist because we are literally struggling there's no way to find any example or documentation to show case or assist in how can we present a document that needs sms for signature using iOS/Android SDK. 

based on the documentation in order to present a template with id you need to use **DSMTemplatesManager**, this manager takes in parameters an **DSMEnvelopeDefaults**, which contains informations about the recipient and takes an array of DSMRecipientDefault.
But how can I tell my Envelope that here's the phone number where the user should receive he's docuSign code to validate a signature. 

using an api this looks like something like that : 
```
 ### SMS APRES
                        recipientSignatureProviders => [{
                            signatureProviderName       => "UniversalSignaturePen_OpenTrust_Hash_TSP",
                            signatureProviderOptions    => {
                                sms                     => $signer_phone,
                            }
                        }],
                        ###
                        ### SMS AVANT
                        # idCheckConfigurationName    => 'SMS Auth $',
                        # smsAuthentication           => {
                        #     senderProvidedNumbers   => [$signer_phone]
                        # },
                        # requireIdLookup             => 'true',
                        ###

```

I was able to find **"idCheckConfigurationName"** in **DSMRecipient** where I can do something like `recipient.idCheckConfigurationName = "SMS Auth"` but no way to add the others informations and difficult to tell how to build a `◆ presentSendTemplateControllerWithTemplateWithId:envelopeDefaults:pdfToInsert:insertAtPosition:signingMode:presentingController:animated:completion:` using this object or how to combine ... 

Thanks in advance for your feedback.

**Comment by soufianeEssabbane** [comment]
anyone to answer ?

**Comment by ashokds** [comment]
Hi @soufianeEssabbane ,
 
Thanks for reaching out. 

Unfortunately, as of current SDK version, it doesn't support the SMS based signatures for a sent document. 

Are you working with a DocuSign Customer Support Professional? If yes, it would help to raise this issue with the DocuSign counterpart to get this on our roadmap with a formal request and get it prioritized.

**Comment by ashokds** [comment]
Opened an internal ticket to include it in the roadmap. Closing it as `SMS Auth` is not available on native-ios-sdk.
