### ISSUE TITLE
Facing issue in running docusign-sdk-sample-swift

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#77]
I tried running the sample app docusign-sdk-sample-swift 

Where it gave an error SVProgresshud is not found. Which is of no use for me then I tried by removing SVProgresshud  which I thought should also work and could of more issues which you need to fix like Standard architecture.

Environment:
1. Xcode 12.4
2. pod version 1.10.1

<img width="930" alt="Screenshot 2021-04-28 at 2 48 13 PM" src="https://user-images.githubusercontent.com/52121407/116379879-11c63b80-a831-11eb-9abe-4b6b42350280.png">

**Comment by ashokds** [comment]
Hi @pushp1010 


I verified the `docusign-sdk-sample-swift` on the [`master` branch](https://github.com/docusign/native-ios-sdk/tree/master/docusign-sdk-sample-swift) with `Xcode12.4` and `cocoa pods 1.10.1`. The swift sample app is working as expected on simulator and devices.

Following the [readme instructions](https://github.com/docusign/native-ios-sdk/blob/master/docusign-sdk-sample-swift/README.md) works as well. 

In order to help you further, could you please try cleaning your project derived data, remove all pods, and perform `pod update`. Please add any error you see with `pod install` and Xcode project build.  

Expected output of `pod install`:

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing DocuSign (2.4.1)
Installing SVProgressHUD (2.2.5)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

Resulting content of `Podfile.lock`:

```
PODS:
  - DocuSign (2.4.1)
  - SVProgressHUD (2.2.5)

DEPENDENCIES:
  - DocuSign
  - SVProgressHUD

SPEC REPOS:
  https://github.com/CocoaPods/Specs.git:
    - DocuSign
    - SVProgressHUD

SPEC CHECKSUMS:
  DocuSign: 78c8172ce9037a2fd41bceddb4b69ba576c42c60
  SVProgressHUD: 1428aafac632c1f86f62aa4243ec12008d7a51d6

PODFILE CHECKSUM: dfbaf3e899a3557c058085ea2be573162bca4e71

COCOAPODS: 1.10.1
```

Thanks.

**Comment by pushp1010** [comment]
@ashokds 
Sorry for the Delay in response

Below is the exact error I am getting while try command "pod install"

[!] Unable to find a specification for `SVProgressHUD`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by ashokds** [comment]
@pushp1010 , 

Your cocoapods cache would need updating with `pod repo update` or `pod install --repo-update`. Did you try this suggestion? 

It takes a while to complete the pod cache update. Once the pods are updated, try `pod install` (if only did update before).

**Comment by pushp1010** [comment]
@ashokds 

Here is log when I tried "pod repo update"

Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/<Systemname>/.cocoapods/repos/cocoapods fetch
  origin --progress
  remote: Enumerating objects: 4865458, done.        
  remote: Counting objects: 100% (2388/2388), done.        
  remote: Compressing objects: 100% (1139/1139), done.        
  remote: Total 4865458 (delta 1249), reused 2244 (delta 1205), pack-reused 4863070        
  Receiving objects: 100% (4865458/4865458), 847.77 MiB | 7.95 MiB/s, done.
  Resolving deltas: 100% (3072937/3072937), done.
  From https://github.com/CocoaPods/Specs
   * [new branch]      amorde/index-script   -> origin/amorde/index-script
   * [new branch]      backz                 -> origin/backz
   * [new branch]      cdn_scripts           -> origin/cdn_scripts
   * [new branch]      igor/fix-workflow     -> origin/igor/fix-workflow
   * [new branch]      indexes               -> origin/indexes
   * [new branch]      master                -> origin/master
   * [new branch]      netlify               -> origin/netlify
   * [new branch]      orta-patch-1          -> origin/orta-patch-1
   * [new branch]      predates_sharding_branch -> origin/predates_sharding_branch
   * [new branch]      swift_version_support -> origin/swift_version_support
   * [new tag]         v0.32.1               -> v0.32.1
   * [new tag]                   20161019              -> 20161019
  $ /usr/bin/git -C /Users/<Systemname>/.cocoapods/repos/cocoapods rev-parse
  --abbrev-ref HEAD
  fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
  HEAD
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
[!] CocoaPods was not able to update the `cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

I tried `pod repo update --verbose` as and below are the log

 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only perfomed in repo update

Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/pushpendrasingh/.cocoapods/repos/cocoapods fetch
  origin --progress
  remote: Enumerating objects: 41, done.        
  remote: Counting objects: 100% (41/41), done.        
  remote: Compressing objects: 100% (26/26), done.        
  remote: Total 27 (delta 16), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     9e8933ab2468..e7834a8a7758  master     -> origin/master
  $ /usr/bin/git -C /Users/pushpendrasingh/.cocoapods/repos/cocoapods rev-parse
  --abbrev-ref HEAD
  fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
  HEAD
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
[!] CocoaPods was not able to update the `cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:178:in `rescue in update_git_repo'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:169:in `update_git_repo'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source.rb:347:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
 
Not sure what is wrong 😑. please help me with this issue

**Comment by ashokds** [comment]
@pushp1010 , 

These issues are related to `cocoapods` setup on your machine. 

Time to time, `pods` cache gets corrupt and cocoapods needs a reset (complete removal and download). To reset pods, you may try suggestions in this post: https://stackoverflow.com/a/46428793/12413715 & https://gist.github.com/mbinna/4202236

At times, it's because of underlying `ruby` changes. It would need some extended debugging on your local machine to figure out the issue with `cocoapods` & `ruby` setup.

**Comment by pushp1010** [comment]
@ashokds Thanks  I will have a look on this and keep you posted on the same.

**Comment by ashokds** [comment]
Closing as it's been resolved.

**Comment by pushp1010** [comment]
@ashokds  it is not resolved yet!

**Comment by ashokds** [comment]
@pushp1010, This is cocoapods related error: `fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.`

Additional suggestions on CocoaPods project to resolve the corrupted pods: https://github.com/CocoaPods/CocoaPods/issues/6077

**Comment by mmohareb** [comment]
closing issue
