### ISSUE TITLE
Fields not populating into template using Swift 

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#78]
@ashokds @iOSSDK-DocuSign  Hi Ashok, 

I tried building my Swift sample Where I am able to login but when I tried to set Tab data but it does not works for me.

below is the screenshot of the Text Id I am using. I am not sure what I am I doing wrong. based on the Documentation and my knowledge it should work.

I have only one template in my account.

<img width="979" alt="Screenshot 2021-05-04 at 6 30 23 PM" src="https://user-images.githubusercontent.com/52121407/117007113-dfbc4a00-ad06-11eb-8cc7-3de57acc4b1e.png">

Below is the code snippet: 

                
                print(template.templateId)
                let recipientDatum = DSMRecipientDefault()
                // Use recipient roleName (other option to use recipient-id) to find unique recipient in the template
                recipientDatum.recipientRoleName = "Lead"
                recipientDatum.recipientSelectorType = .recipientRoleName
                recipientDatum.recipientType = .inPersonSigner
                // In-person-signer name
                recipientDatum.inPersonSignerName = "Pushpendra Singh"
                // Host name (must match the name on the account) and email
                recipientDatum.recipientName = "pushpendra singh"
                recipientDatum.recipientEmail = "psinghiosdeveloper@gmail.com"
                
                let textCustomField = DSMTextCustomField()
                textCustomField.name = "Text 06a6bafd-991f-438c-8df2-2f13dc114609"
                textCustomField.value = "Tom Wood"
                textCustomField.show = true

                
                let tabData1: [String: String] = ["Text 06a6bafd-991f-438c-8df2-2f13dc114609": "jas"]
                
                let customFields = DSMCustomFields()
                customFields.textCustomFields = [textCustomField]
                
                TemplatesManager.sharedInstance.displayTemplateForSignature(templateId: template.templateId, controller: self.viewController!, tabData: tabData1, recipientData: [recipientDatum], customFields: customFields, onlineSign: true, attachmentUrl: nil) { (controller, error) in
                    
                    print(controller, error)
                }

I am trying onlineSign It should work. Please put on some light here.

**Comment by pushp1010** [comment]
https://github.com/docusign/native-ios-sdk/issues/14 This issue does not works for me please help

**Comment by ashokds** [comment]
Hi @pushp1010 , 

Thanks for creating a separate issue and adding details with sample code. 

I see that you are using [Text Custom Fields](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopecustomfields/). 

```
let textCustomField = DSMTextCustomField()
textCustomField.name = "Text 06a6bafd-991f-438c-8df2-2f13dc114609"
textCustomField.value = "Tom Wood"
textCustomField.show = true
```

This would add a `text custom field` to the envelope, and it'll be part of the `certificate of completion`. These fields won't update any Text based tabs, rather `Text & List Custom Fields` are used for setting envelope meta data. 


What you are looking for is to set the `DSMEnvelopeDefaults.tabValueDefaults`. `tabValueDefaults` is a `Dictionary<String,String>` type and it can be used to assign values for given tab-labels. You could do:

```
envelopeDefaults.tabValueDefaults = ["Text 06a6bafd-991f-438c-8df2-2f13dc114609","jas"] 
```


For other relevant details, please take a look at `DocuSignViewController` of [Swift Sample app](https://github.com/docusign/native-ios-sdk/tree/master/docusign-sdk-sample-swift).

- [Line 29:](https://github.com/docusign/native-ios-sdk/blob/c76a7a0d036ddaad004b60249462521074762d77/docusign-sdk-sample-swift/docusign-sdk-sample-swift/Controllers/DocuSignViewController.swift#L29) Invokes ProfileManager to prepare defaults data. 
`let tabData: Dictionary = ProfileManager.sharedInstance.getTemplateTabData(templateId:templateId)`
- And this `tabData` is later on [assigned to `envelopeDefaults.tabValueDefaults`](https://github.com/docusign/native-ios-sdk/blob/c76a7a0d036ddaad004b60249462521074762d77/docusign-sdk-sample-swift/docusign-sdk-sample-swift/Managers/TemplatesManager.swift#L96).
```
let envelopeDefaults = DSMEnvelopeDefaults()
envelopeDefaults.recipientDefaults = recipientData.count > 0 ? recipientData : nil
envelopeDefaults.tabValueDefaults = tabData
envelopeDefaults.customFields = customFields
```

**Comment by pushp1010** [comment]
Sorry But did not get 

`envelopeDefaults.tabValueDefaults = ["Text 06a6bafd-991f-438c-8df2-2f13dc114609","jas"] 
`

I believe this [string: string] in swift then it should 

``envelopeDefaults.tabValueDefaults = ["Text 06a6bafd-991f-438c-8df2-2f13dc114609": "jas"] 
``

Then it should show the data in the template right?

**Comment by ashokds** [comment]
It should be working for your setup. Could you please attach the template json here: [how to download template](https://support.docusign.com/en/guides/ndse-user-guide-download-template).

Also, when you start the online signing ceremony using SDK, do you see your envelope-document with the text-tab? 


Note: By default, SDK usage `DSMTabComparisonStrictMatch` for `tabLabel` comparison. In `AppDelegate`, you may use less restrictive matching with the following config.

```
configurations[DSM_SETUP_TAB_DEFAULTS_COMPARISON] = DSMTabComparisonContains.rawValue // or DSMTabComparisonCaseAndDiacriticInsensitive.rawValue
DSMManager.setup(withConfiguration: configurations)
```

**Comment by pushp1010** [comment]
can we jump on a quick call on teams?

**Comment by pushp1010** [comment]
Here is the downloaded template  
[DocuSignTemplates_May_5_2021_05_49_34.zip](https://github.com/docusign/native-ios-sdk/files/6425285/DocuSignTemplates_May_5_2021_05_49_34.zip)

**Comment by ashokds** [comment]
Looking at the template json, `tabLabel` is set as `Text Fullname` on the template. (From JSON: `"tabLabel": "Text Fullname",`)

Try following: `let tabData1: [String: String] = ["Text Fullname": "jas"]`

for `"templateId": "ce4adbf7-c840-4807-befd-304ed5eb9ab0",`

**Comment by pushp1010** [comment]
@ashokds Yeah I tried with sam but still no success yet! Waiting for you over zoom call See you there 😊

**Comment by ashokds** [comment]
Glad that it worked after the meeting. 

Good to note here that SDK and DocuSign APIs does case sensitive matching for the signer name/email. 

Another note regarding `prefillTabs`, sdk doesn't support `prefillTabs` and will skip these.
```
            "tabs": {
                "prefillTabs": {
                    "textTabs": [
                        { ... }
            ...
```

Thanks.
