### ISSUE TITLE
DocuSing API return content-type exception

### ISSUE THREAD

**Issue by vijaypalve** [docusign/native-ios-sdk#8]
I have implemented DocuSign authentication API. It throws exception "Content-Type"
Please find the attached screen shots.

![request](https://user-images.githubusercontent.com/14092016/41329757-157b54f2-6eed-11e8-8513-c5ecc97be449.png)
![reuest1](https://user-images.githubusercontent.com/14092016/41329815-680cbd8c-6eed-11e8-8a3a-30a0f84dfaf9.png)

![content-type exception](https://user-images.githubusercontent.com/14092016/41329758-15b83bf6-6eed-11e8-9704-839a28c211c9.png)

**Comment by mmallis87** [comment]
@vijaypalve is there any chance you can use the [official DocuSign Nuget package](https://github.com/docusign/docusign-csharp-client)?

**Comment by vijaypalve** [comment]
@mmallis87  Thank you for the reply.

I have implemented application using Xamarin.Forms. Thats why I am using DocuSign API's and is there any change to use DocuSign package in Xamarin.Forms?

**Comment by iOSSDK-DocuSign** [comment]
@vijaypalve 
Would it be possible for you to attach a project that reproduces the API error blocking you? We don't officially support Xamarin, may take a look.

**Comment by vijaypalve** [comment]
@iOSSDK-DocuSign  Thank you for the reply

Please the attached project


[DocuSign_XF1.zip](https://github.com/docusign/iOS-offline-templates-sdk/files/2097970/DocuSign_XF1.zip)

**Comment by vijaypalve** [comment]
@iOSSDK-DocuSign 

 Did you get a chance to see conten-type issue?

**Comment by vijaypalve** [comment]
@iOSSDK-DocuSign 

Content-Type issue resolved after using below code :

`client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));`

![rest call](https://user-images.githubusercontent.com/14092016/41411455-905995a4-6ffa-11e8-8681-6f7e5da544a2.png)


But after sending request apI throws a task was canceled exception :

![taskcancel](https://user-images.githubusercontent.com/14092016/41411195-91173470-6ff9-11e8-8738-5b590c400d40.png)

**Comment by ashokds** [comment]
Closed as no longer active.
