### ISSUE TITLE
Envelope is ready for sync and cannot be resumed for signing.

### ISSUE THREAD

**Issue by SayaniC** [docusign/native-ios-sdk#80]
Hi,

I want to sign a PDF, which is present in the ios application bundle.
DSMEnvelopesManager().composeEnvelope(with: envelope, signingMode: .offline) { (envelopeId, error) in
                print(envelopeId)
                if let envelopeId = envelopeId {
                    DSMEnvelopesManager().resumeSigningEnvelope(withPresenting: self, envelopeId: envelopeId) { (controller, error) in
                        print(controller)
                        print(error)
                    }
        }
        
Getting error "Envelope is ready for sync and cannot be resumed for signing." when I call resumeSigning.
       
Can't seem to find sample code around this and the steps mentioned in the ReadMe file did not work. It's not there in the sample app as well.

Could you please help me out?

**Comment by SayaniC** [comment]
Also, if I try to composeEnvelope in online mode then envelopeId is returning nil and not able to proceed after that.

**Comment by SayaniChakraborty** [comment]
Adding few more questions:
1) Not able to set tabValueDefaults. It's not working in the sample project as well. I saw the solutions mentioned (adding DSMRecipientDefault), but that also did not work.

2) Is there a way to bypass the recipient screen and directly take the user to the signing page?

**Comment by SayaniC** [comment]
Adding few more questions:

1. Not able to set tabValueDefaults. It's not working in the sample project as well. I saw the solutions mentioned (adding DSMRecipientDefault), but that also did not work.
2. Is there a way to bypass the recipient screen and directly take the user to the signing page?

**Comment by bharadwaj465** [comment]
@SayaniC ,

#### 1:`Getting error "Envelope is ready for sync and cannot be resumed for signing." when I call resumeSigning.`
This error would occur when there are no pending local signers to sign the document. To perform signing, the recipient should be either an in-person signer of the host or the host.

If the recipient is a remote signer other than the host (the one who logged into the DocuSignSDK), you can only sync the offline envelope.

For example, if the recipient who logged into SDK is `John Doe, johndoe@gmail.com` 
You can resume signing only for 
    1.  an inperson signer with hostname/ hostemail as `John Doe, johndoe@gmail.com` 
    2. host himself as a remote signer.
   
#### 2: `Not able to set tabValueDefaults. It's not working in the sample project as well. I saw the solutions mentioned (adding DSMRecipientDefault), but that also did not work.`

To set tabValueDefaults when using **Templates**, make sure TabLabel exactly matches with the tabLabel field on the Template json (not **tabId**)
**tabLabel	:	Text 7e19ecfe-8a00-4fcb-96bb-b20bdb7894bb**

#### 3:` Is there a way to bypass the recipient screen and directly take the user to the signing page?`
If all the recipients have defaulted for the **Template**  using **DSMRecipientDefaults**, then you won't see a UI to add recipient details. Directly you will be taken to either recipient selection screen (if multiple recipients are in the same routing order) or signing page. 

If the problem still exists, please provide more details, such as tab details, recipient defaults, and the template's json (can be downloaded from DocuSign's website).

**Comment by SayaniChakraborty** [comment]
@bharadwaj465,

1. If the recipient is a remote signer other than the host (the one who logged into the DocuSignSDK), you can only sync the offline envelope. ---- Did not understand. Does this mean online flow will not work at all?
In my case host and signers are different. In person signer worked for me only in offline mode and after that DSMEnvelopesManager().syncEnvelopes() did not work. I am not able to see the signed docs on Docusign portal.

Also, once I add a signature in this flow, I am not able to edit it again. Is that expected?

2. I am using tabLabel only. 
▿ 6 elements
  ▿ 0 : 2 elements
    - key : "Text bfcee4e8-adb8-4cd4-8e53-85afd75c416b"
    - value : "726 Tennessee St"
  ▿ 1 : 2 elements
    - key : "Text 11c675fe-b596-4adf-a48e-8684b2757b97"
    - value : "Tom Wood"
  ▿ 2 : 2 elements
    - key : "Text 88dd31f3-bc32-4fa1-959a-cd7c91f2f23e"
    - value : "U.S.A. 94107"
  ▿ 3 : 2 elements
    - key : "Text b646d8bd-031b-40d7-9927-eb3a71ae3ad0"
    - value : "San Francisco, California"
  ▿ 4 : 2 elements
    - key : "Text 3ff69c25-ea75-4cdc-9789-4c92d70b5e33"
    - value : "FA-45231-005"
  ▿ 5 : 2 elements
    - key : "Text 6354219d-a9fd-45e6-8b68-3ed544993dbb"
    - value : "$25,000.00"

[DocuSignTemplates_May_18_2021_16_59_17.zip](https://github.com/docusign/native-ios-sdk/files/6503175/DocuSignTemplates_May_18_2021_16_59_17.zip)

**Comment by bharadwaj465** [comment]
> 1. If the recipient is a remote signer other than the host (the one who logged into the DocuSignSDK), you can only sync the offline envelope. ---- Did not understand. Does this mean online flow will not work at all?
>    In my case host and signers are different. In person signer worked for me only in offline mode and after that DSMEnvelopesManager().syncEnvelopes() did not work. I am not able to see the signed docs on Docusign portal.

In your case, after the in-person signer signs the envelope, it will be sent to the **remote signer** after the sync. A remote signer can sign the envelope from `the email received/Docusign's Web portal/Docusign's Mobile App.` You can listen to our [sync notifications](https://developers.docusign.com/docs/ios-sdk/refdocs/html/_d_s_m_notification_codes_8h.html) for more details about the envelope.  
Observe: `DSMEnvelopeSyncingStartedNotification`, `DSMEnvelopeSyncingSucceededNotification` ,  `DSMEnvelopeSyncingFailedNotification`, `DSMEnvelopeSyncingEndedNotification` to get specific errors.

If there are no errors, on successful sync, you can track the envelope from DocuSign's web portal from Manage --> Quick Views  --> Waiting for Others.

<img width="248" alt="quick views" src="https://user-images.githubusercontent.com/9475547/118813970-4cba0d00-b8cd-11eb-97d8-ef9d01caeccf.png"> 

Make sure to use our [Envelope Builders ](https://github.com/docusign/native-ios-sdk/blob/master/Compose-Envelope.md)to prepare envelope when using the below method. This way, you can capture errors early by using try-catch blocks.

`DSMEnvelopesManager().composeEnvelope(with: envelope, signingMode: .offline) { (envelopeId, error) in
`


> Also, once I add a signature in this flow, I am not able to edit it again. Is that expected?

Yes, once you confirm and adopt the signature, you cannot change it. However, you can clear your signature multiple times before adopting it.


> I am using tabLabel only. 

I will get back to you on this after further investigation.

**Comment by SayaniChakraborty** [comment]
@bharadwaj465 Thanks for the response!

But my issue is after signing the envelope in offline mode, DSMEnvelopesManager().syncEnvelopes() is failing. I already added the sync envelope notification observers.

Let me know if you need any additional info.

**Comment by bharadwaj465** [comment]
@SayaniC ,

1) When sync fails, you would receive `DSMEnvelopeSyncingFailedNotification.` Could you please add `userInfo` details on `DSMEnvelopeSyncingFailedNotification` ?

2) Please attach a sample project with the code used for integrating DocuSign flows (like envelope creation, setting defaults for the template used)?  Please remove all the sensitive information like `integrator key`, `email ids` and add placeholders instead.

**Comment by SayaniChakraborty** [comment]
@bharadwaj465 
Failure response:
Optional([AnyHashable("transactionId"): E4210BC3-BC09-48AD-B118-59ADCE298550, AnyHashable("cacheURI"): E4210BC3-BC09-48AD-B118-59ADCE298550, AnyHashable("envelopeId"): E4210BC3-BC09-48AD-B118-59ADCE298550])

**Comment by SayaniChakraborty** [comment]
Not able to attach the sample project. It's failing. PFA the controller file.

[ViewController.swift.zip](https://github.com/docusign/native-ios-sdk/files/6517207/ViewController.swift.zip)

**Comment by SayaniChakraborty** [comment]
Any update on this issue?
