### ISSUE TITLE
Not able to login 

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#84]
Not sure  Why I am getting below error

Account: Optional(<DSMAccountInfo: 0x6000011e8540>), Error: Optional(Error Domain=user.additional.data.fetch.error Code=-1011 "Unable to fetch additional data for user - The URL provided does not resolve to a resource. Consumer Disclosure does not exist." UserInfo={DSM_com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x600003504620> { URL: https://demo.docusign.net/restapi/v2/accounts/13992435/consumer_disclosure } { Status Code: 404, Headers {

    "Cache-Control" =     (

        "no-cache"

    );

    "Content-Length" =     (

        143

    );

    "Content-Type" =     (

        "application/json; charset=utf-8"

    );

    Date =     (

        "Thu, 27 May 2021 12:18:14 GMT"

    );

    Vary =     (

        "Accept-Encoding"

    );

    "X-BurstLimit-Limit" =     (

        500

    );

    "X-BurstLimit-Remaining" =     (

        496

    );

    "X-DocuSign-Node" =     (

        DA2DFE188

    );

    "X-DocuSign-TraceToken" =     (

        "29004bd3-75fd-4b11-a694-747cb425a6b0"

    );

    "X-RateLimit-Limit" =     (

        1000

    );

    "X-RateLimit-Remaining" =     (

        991

    );

    "X-RateLimit-Reset" =     (

        1622120400

    );

} }, DSESResponseObject={

    errorCode = "RESOURCE_NOT_FOUND";

    message = "The URL provided does not resolve to a resource. Consumer Disclosure does not exist.";

}, NSErrorFailingURLKey=https://demo.docusign.net/restapi/v2/accounts/13992435/consumer_disclosure, DSM_com.alamofire.serialization.response.error.data={length = 143, bytes = 0x7b0d0a20 20226572 726f7243 6f646522 ... 6973742e 220d0a7d }, NSLocalizedFailureReason=RESOURCE_NOT_FOUND, NSLocalizedDescription=Unable to fetch additional data for user - The URL provided does not resolve to a resource. Consumer Disclosure does not exist.})

**Comment by vietnguyebkhn** [comment]
Have you solved the problem yet?
I am also facing the same problem in SwiftUI demo. I can't login with login withAccessToken

**Comment by pushp1010** [comment]
@vietnguyebkhn  Unfortunately no

**Comment by saimt** [comment]
Hi, I'm facing the same error. Any luck so far?

**Comment by ashokds** [comment]
Hi @vietnguyebkhn , @pushp1010 , @saimt :

Please note that [`v2.5` deprecated the legacy login methods](https://github.com/docusign/native-ios-sdk/blob/master/CHANGELOG.md). And only supported method `v2.5` onwards is `loginWithAccessToken`. 

[`v2.4.1`](https://github.com/docusign/native-ios-sdk/tree/v2.4.1) is the last version that didn't deprecate the legacy login methods. 

Deprecated `loginWithApiPassword:...` and `loginWithEmail:` methods are planned for complete removal during Q4 2021 release. Some details on acquiring `AccessToken` for sdk-login below:

## User Authentication (v2.5 update)

Following [DSMManager](https://github.com/docusign/native-ios-sdk/blob/master/DocuSignSDK.framework/Headers/DSMManager.h) method is the recommended interface to use once the client-app has a valid access token -- additional details on how to [get an access token](https://developers.docusign.com/platform/auth). Once authenticated, [userinfo](https://developers.docusign.com/platform/auth/reference/user-info/) can be used to fetch additional properties such as `userId`, `username`, etc required for login.


```
/*!
 @method loginWithAccessToken
 @brief Sets up DocuSign user account for SDK usage in OAuth case.
 @param accessToken  DocuSign oAuthToken
 @param accountId  DocuSign accountId of the user using SDK for sign and send
 @param userId  DocuSign userId of the user using SDK for sign and send
 @param userName  DocuSign username of the user using SDK for sign and send
 @param email  DocuSign registered email Id of the user using SDK for sign and send
 @param host  DocuSign host where user is signed up with DocuSign (e.g. "https://demo.docusign.net/restapi")
 @param integratorKey DocuSign integratorKey for the client application
 @param completion block to be executed after user account is setup
 @see DSMAccountInfo.h
 */
+ (void)loginWithAccessToken:(NSString *)accessToken
                   accountId:(NSString *)accountId
                      userId:(NSString *)userId
                    userName:(NSString *)userName
                       email:(NSString *)email
                        host:(NSURL *)host
               integratorKey:(NSString *)integratorKey
                  completion:(void(^)(DSMAccountInfo *_Nullable accountInfo, NSError *_Nullable error))completion;
```

**Comment by ashokds** [comment]
Regarding `Unable to fetch additional data for user - The URL provided does not resolve to a resource` error:

Please create a `Consumer Disclosure` on the account by following this guide: https://support.docusign.com/en/guides/ndse-admin-guide-legal-disclosure

Thanks.

**Comment by mmohareb** [comment]
Closing this issue
