### ISSUE TITLE
Not able to set navigation bar appearance

### ISSUE THREAD

**Issue by SayaniChakraborty** [docusign/native-ios-sdk#91]
Using the following functions for setting it.

DSMAppearance.setNavigationBarTintColor(UIColor.red)
DSMAppearance.setBarButtonItemsTintColor(UIColor.white)

**Comment by bharadwaj465** [comment]
This needs to be set only after DSMManager.setup() method.  Can you confirm if it's in right place?

**Comment by mmohareb** [comment]
closing this issue
