### ISSUE TITLE
Help needed for setting brandId

### ISSUE THREAD

**Issue by SayaniChakraborty** [docusign/native-ios-sdk#92]
Can you please provide a sample code for setting brand id while presenting a template?

**Comment by ashokds** [comment]
Hi @SayaniChakraborty :

As of the latest release, iOS-SDK doesn't support configuring brand resources directly. It's best to use [the admin guide to configure brands](https://support.docusign.com/en/guides/ndse-admin-guide-configure-branding) directly on the DocuSign Web. 

Please note that once the brand resources are configured, iOS-SDK would use those for **Online Signing**.

Thanks for bringing it up to our attention.
