### ISSUE TITLE
Question regarding documentId parameter

### ISSUE THREAD

**Issue by jnotting** [docusign/native-ios-sdk#93]
We are trying to create an envelope using the DSMDocumentBuilder class but ran into an issue when defining the documentId parameter.  The SDK documentation indicates documentId is a string however we see conflicting errors in the DocuSign API server logs.  We see in the DocuSign API server logs in the console an error that says: "The request contained at least one invalid parameter.  The documentId specified is not a positive integer.  

Can you please clarify?  Thanks!

**Comment by dmartin00** [comment]
Hello,

A Document ID does need to be a positive integer lower than 2147483647. Unfortunately, the current version of our API has parameters that are not correctly typed. We do have an internal project to strongly-type our API, but that looks to be a ways out.

**Comment by jnotting** [comment]
Thank you.
