### ISSUE TITLE
Create Envelope API

### ISSUE THREAD

**Issue by jnotting** [docusign/native-ios-sdk#94]
With the Android SDK, we are able to mimic our cloud API service by using DocuSign.getInstance().getESignApiDelegate().createApiService(EnvelopesApi::class.java) to create an envelope using a server template ID.  

Is there an equivalent createAPI function for the iOS SDK that would allow us to accomplish the same thing or are there plans to implement one?  I was unable to find it in the documentation.

Thanks

**Comment by bharadwaj465** [comment]
You can use the following method listed on `DSMTemplatesManager` to create and sign the envelope from `templateId`.

Please refer this documentation for more details : [Present Template](https://developers.docusign.com/docs/ios-sdk/refdocs/html/interface_d_s_m_templates_manager.html#a61cd680e2fbcf03d822c2130a6e714b8) or [Present Template with defaults](https://developers.docusign.com/docs/ios-sdk/refdocs/html/interface_d_s_m_templates_manager.html#afd49fe457b484592b4d25bfaedb01d7b)
