### ISSUE TITLE
Having issue with envelop sync process 

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#96]
@ashokds @Harinder @hassaan22 @jeff00seattle @stephenparish @thomas-dang 

I am trying to sync all the envelopes which I have sign recently. but 

`
   self?.envelopManager.syncEnvelopes()
`
Is able to sync one envelop at a time? Is there any way to fix this?

**Comment by ashokds** [comment]
Hi @pushp1010 ,

`self?.envelopManager.syncEnvelopes()` syncs all of the offline signed envelopes. 

Sync service only allows sending all envelopes when the client app triggers `syncEnvelopes()`.

Thanks.

**Comment by pushp1010** [comment]
@ashokds  

Here are the cases


	
When I signed multiple documents and I can see the documents in cache but when i call “self?” , it sync only one document and leaves the other in cache.
	
When I have only one document in the cache, sync does not work. Even after calling it forcefully in SignCompleteNotificationCallback.


It always pick the top element present at first index and leaves the rest, even after calling in syncSucceededNotification callback.

I am using version 2.4.1 because 2.5.1 had a crash while creating a document. That crash is also reported below:
https://github.com/docusign/native-ios-sdk/issues/89​​​​​​​

**Comment by pushp1010** [comment]
@ashokds @Harinder @hassaan22 @jeff00seattle @stephenparish @thomas-dang  We need help on this. Its urgent as we got stuck on it

**Comment by ashokds** [comment]
@pushp1010 , 

Added new info to [pull the fix](https://github.com/docusign/native-ios-sdk/issues/89) for issue #89, please check it.

Regarding sync, do you have listeners for sync related notifications in place and are you getting error with `userInfo` for failures `DSMEnvelopeSyncingFailedNotification`? Could you please try it on a fresh install app after upgrading to latest pod: `pod 'DocuSign', :git => 'https://github.com/docusign/native-ios-sdk.git', :branch => "release/2.5.3-beta"`. 

Please paste the error and other specific details you get via notification's `userInfo`. Relevant notifications from [DSMNotificationCodes.h](https://github.com/docusign/native-ios-sdk/blob/release/2.5.3-beta/DocuSignSDK.framework/Headers/DSMNotificationCodes.h)

```
/*!
 * @brief Notification sent when process to start syncing cached-envelopes with DocuSign server either finishes normally or is terminated preemptively.
 * @discussion Returns userInfo as nil. This can be posted on a thread other than MainThread.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMEnvelopeSyncingEndedNotification object:nil];
 */
extern NSString * const DSMEnvelopeSyncingEndedNotification;

/*!
 * @brief Notification sent when process to start syncing cached-envelopes with DocuSign server begins.
 * @discussion Returns userInfo with envelopes pending sync details. This can be posted on a thread other than MainThread. Each of the entries contains the dictionary of {DSMEnvelopeIdKey: envelopeId, DSMTemplateIdKey: templateId, DSMTransactionIdKey: transactionId} representing an envelope instance.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMEnvelopeSyncingStartedNotification object:nil];
 */
extern NSString * const DSMEnvelopeSyncingStartedNotification;

/*!
 * @brief Notification sent when process to start syncing cached-envelopes with DocuSign server fails because of some error.
 * @discussion Returned userInfo has envelopeId (cache URI) associated with DSMCacheURIKey key. This can be posted on a thread other than MainThread.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMEnvelopeSyncingFailedNotification object:nil userInfo:userInfo];
 */
extern NSString * const DSMEnvelopeSyncingFailedNotification;

/*!
 * @brief Notification sent when process to sync a cached-envelope succeeds with DocuSign server.
 * @discussion Returned userInfo contains: envelopeId associated with DSMEnvelopeIdKey, cache URI associated with DSMCacheURIKey and templateId associated with DSMTemplateIdKey. This can be posted on a thread other than MainThread.
 * [[NSNotificationCenter defaultCenter] postNotificationName:DSMEnvelopeSyncingSucceededNotification object:nil userInfo:userInfo];
 */
extern NSString * const DSMEnvelopeSyncingSucceededNotification;

``` 

Thanks.

**Comment by pushp1010** [comment]
@ashokds  Thanks for the reply.

I have all the Notification implemented but not getting error. I will prepare a video of this issue for you so that you can fix this in upcoming version

**Comment by pushp1010** [comment]
@ashokds below are the logs:

**I started with print the logs with notification** 
**Local envelopID is below** 
Optional([AnyHashable("envelopeId"): 284C5CBD-1F9A-44C9-AC25-00F05F376516, AnyHashable("signingMode"): offline])
envelopManager.cachedEnvelopes ["284C5CBD-1F9A-44C9-AC25-00F05F376516"]
**signCompleted successfully**. **SignCompletedNotification fired here  but there is not sync happening after this all though the above code is placed** 

**Next Document signing started here**
Optional(<DSMNavigationController: 0x7f888f81a800>)
nil

Optional([AnyHashable("envelopeId"): A8125C31-7D48-418C-B9B2-610F65F2B1EF, AnyHashable("signingMode"): offline])
envelopManager.cachedEnvelopes ["284C5CBD-1F9A-44C9-AC25-00F05F376516", "A8125C31-7D48-418C-B9B2-610F65F2B1EF"]   **Here we two enveloper which are to signed** 
signCompleted successfully **SignCompletedNotification fired here  but this time sync will also takes place you can see the below logs** 
Optional([AnyHashable("284C5CBD-1F9A-44C9-AC25-00F05F376516"): {
    envelopeId = "284C5CBD-1F9A-44C9-AC25-00F05F376516";
    templateId = "";
    transactionId = "284C5CBD-1F9A-44C9-AC25-00F05F376516";
}])
envelopManager.cachedEnvelopeIds ["284C5CBD-1F9A-44C9-AC25-00F05F376516"]
syncStarted successfully **Sync started notification** 

envelopManager.cachedEnvelopeIds ["A8125C31-7D48-418C-B9B2-610F65F2B1EF"]
syncSucceeded successfully **Sync Succeed  notification and it has synced the one I have signed earlier and still has one envelop left which will never sync** 

**I am calling the same method which is mentioned above as  which says all envelop will get synced but it is syncing one at time. Even after calling it force will in Sync succeeded notification it does sync the last envelope.**

**I hope the above information will help you debug this. If you still need some information then lets jump on to a call to sync better. Thanks in Advance!**

**Comment by pushp1010** [comment]
@ashokds  let me know when can we sync over this issue?

**Comment by ashokds** [comment]
@pushp1010 , 

Thanks for the meeting today and for walking us through your use case. In your current implementation, `DSMSigningCompletedNotification` is used to trigger `sync` immediately -- and it causes the sync to miss the `just signed envelope` as it's not saved on the device by that time. 

Could you trigger `sync` when you receive the `DSMEnvelopeCachedNotification` instead? Envelope cached notification is sent out when a) Envelope is saved b) User finishes signing and exists the ceremony. So the order is first `DSMSigningCompletedNotification` is sent out, envelope data is cached and `DSMEnvelopeCachedNotification` sent out next. 

```
... 
             // register for envelope cached notification
             [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleEnvelopeCachedNotification:) name:DSMEnvelopeCachedNotification object:nil];
....


- (void)handleEnvelopeCachedNotification:(NSNotification *)notification {
    NSString *message = [NSString stringWithFormat:@"[sample-app]-Received Notification: DSMEnvelopeCachedNotification: %@", notification];
    [self sync]; // client would like to trigger sync immediately after receiving the cached notification.
}
```

Finally, in order to confirm it synced properly, check the `completed` section on docusign.com.

<img width="637" alt="Screen Shot 2021-09-22 at 2 55 53 PM" src="https://user-images.githubusercontent.com/17131511/134427612-796c2975-9b62-47c8-9b6f-cbd10f7fab52.png">

**Comment by ashokds** [comment]
Marking it as resolved.
