### ISSUE TITLE
How corretly use DSMManager.login(withAccessToken:

### ISSUE THREAD

**Issue by VadymLiakutin** [docusign/native-ios-sdk#98]
Now we add Auth token 
DSMManager.login(
                withAccessToken: "eyJ0eXAiOiJNia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQoAAAABAAUABwAAUOgTEnnZSAgAAJALIlV52UgCAAh2_vNW6T1CuseluTpL0LAVAAEAAAAYAAEAAAAFAAAADQAkAAAAZThmNjRiYTgtZTE4Ni00NDUyLTg2ZmEtZGE4NjcxMDhkNjJjIgAkAAAAZThmNjRiYTgtZTE4Ni00NDUyLTg2ZmEtZGE4NjcxMDhkNjJjMAAApf1vD3nZSDcAkmivoPiCpkWLhlgHVcHO8Q.i8S7YX3l8mQU0Ufq_hMZvzfw09IrADsBGo4WaRYdwF75kC_5p3ckYBZOJblkrly6k5-H-vHjwX_Da7RpdMQAOhb-3EtwBMPHkBbDBq_gJPDTzhY65JqutXGwlGmA-2IYwl2rJc-5OjmIaYwUDpsNZmHI0-o8v0SJy2mRm_RJHFv7wfLL7Ku0Oboqtbg9t8X3iWgK2hKB_jwzANzCiz8s8LK202is7YqhAhcSUjQnViHxPM17XI0ihuJQ2b79aXdDtCBUkmZiH71aNhbU0HGPkMbK9Ort7CIB3dLS5zjXBL3MA1PA2CCop-naT0xGT-KWsotIJYQyNNkkuTZgEocy7w",
                accountId: "xxxx198xx",
                userId: "f3fe7608-xxxx-423d-bac7-xxxx3a4bd0b0",
                userName: "Vxxxx Lxxxx",
                email: "vxxxxxx.lxxxxxxn@xxxxxxx.com",
                host: URL(string: "https://account-d.docusign.com/")!,
                integratorKey: "e8f6xxxxx-e186-4452-86fa-xxxx7108d62c"
            ){

On API data get successfully

**Comment by mmohareb** [comment]
Can you please explain what is needed for this request?

**Comment by mmohareb** [comment]
Closing this issue
