### ISSUE TITLE
UIViewController is missing its initial trait collection populated during initialization.

### ISSUE THREAD

**Issue by VadymLiakutin** [docusign/native-ios-sdk#99]
After update iOS to 15 version I was get this error.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UIViewController is missing its initial trait collection populated during initialization. This is a serious bug, likely caused by accessing properties or methods on the view controller before calling a UIViewController initializer. View controller: <DSMPassViewController: 0x13f82f800>'

**Comment by ashokds** [comment]
Hi @VadymLiakutin 

Fix for this issue is planned for `v2.7` release in the coming week.

**Comment by mmohareb** [comment]
https://github.com/docusign/native-ios-sdk/pull/107

**Comment by scott-clampet-mh** [comment]
What was the solve for this issue?

**Comment by mmohareb** [comment]
This was fixed with the SDK release 2.7
